### ISSUE TITLE
Multiple Controllers

### ISSUE THREAD

**Issue by Harjot1Singh** [KhalisFoundation/sttm-desktop#10]
Given that this is practically a web app, why not expose the controller over the network so web clients (e.g. on mobile) can also control STTM? https://github.com/ShabadOS/core does this, and I think this is a good direction to take. 

I've actually been looking at both projects this evening, and was evaluating both. I think it's wonderful that we've got some development infrastructure around these sorts of apps, but I feel it would be better to place all manpower for a desktop/projector/Gurdwara app in one place.

Why not merge the development of these apps, rather than replicating each other's efforts?

**Comment by navdeepsinghkhalsa** [comment]
@Harjot1Singh Thank you for your comments, Singh Jee. In fact, the ShabadOS team and this team did resolve to work on this project together to combine efforts toward a single platform just like you suggested.

In addition, the feature you've requested is a planned offering, yes. I will mark this request as closed, but please feel free to discuss further.

**Comment by Harjot1Singh** [comment]
Ah, where are the efforts being focused? Currently, I’ve been recommending shabadOS, since the featureset seemed more complete, and was going to submit some PRs there.

**Comment by Harjot1Singh** [comment]
Misread. What was the reasoning behind focusing here?
