### ISSUE TITLE
Controller App Lag

### ISSUE THREAD

**Issue by ManjotS** [KhalisFoundation/sttm-desktop#1008]
Please select which platform you are using:-
Mobile App

Feedback Type
Bug Reports

What went wrong?
Issue:
Today there is lot of delay when using controller app.
Other good thing
Now I was able to see the box to enter code and pin very first time so Old issue seems to be fixed thanks 

 
What should have happened instead?
Last week there was no delay
    
How can the issue be recreated by our team?
Use controller app on iphone

Which web browser are using?
Safari 

Operating System
Mac OS

Name
Rajpal singh  Bajaj

**Comment by inderpreetsingh** [comment]
I am not sure I understand this one properly.
