### ISSUE TITLE
Announcements: space bar doesn't work

### ISSUE THREAD

**Issue by ManjotS** [KhalisFoundation/sttm-desktop#1010]
Please select which platform you are using:-
Desktop Version

Feedback Type
Bug Reports

What went wrong?
in the announcement section the space bar doesn't work. This started happening in latest version. 
 
What should have happened instead?
space bar should work
    
How can the issue be recreated by our team?
try to type, space bar doesn't work

Which web browser are using?
Chrome 

Operating System
Microsoft Windows

Name
Naveen Mata

**Comment by maneetpaul** [comment]
Duplicate ticket
