### ISSUE TITLE
Time to rethink navigator interface.

### ISSUE THREAD

**Issue by inderpreetsingh** [KhalisFoundation/sttm-desktop#104]
With all the new features and options, navigator is bloated with too many options which are organized rather sparingly. On a couple of user testings in and around my house I found users rather confused and struggling to find features, confirming my doubt. I believe we need to move a lot of options outside that small navigator window and place them somewhere more appropriate. Will show some mockups soon.

**Comment by ManjotS** [comment]
@inderpreetsingh @navdeepsinghkhalsa I would prefer we bring back the original prefs screen if this is a goal (screenshot in this ticket https://github.com/KhalisFoundation/sttm-desktop/issues/20)

The code is already created and the interface was good.

**Comment by tarunsingh5** [comment]
obsolete given new ui
