### ISSUE TITLE
Floral theme improvements for Bani Overlay

### ISSUE THREAD

**Issue by saintsoldierx** [KhalisFoundation/sttm-desktop#1047]
The colors for floral theme are clashing and not great contrast. Please try following colors...

background pink
RGBA: 255 122 178 1

secondary text (teeka etc)
rgb(87, 5, 50)

![image](https://user-images.githubusercontent.com/27791330/78510316-355fa500-7749-11ea-9ff8-0e6bc651066c.png)

**Comment by Gauravjeetsingh** [comment]
Fixed and released to production.
