### ISSUE TITLE
Bani Controller keeps jumping around 

### ISSUE THREAD

**Issue by maneetpaul** [KhalisFoundation/sttm-desktop#1101]
This isn't very consistent, but it's happening a lot where I will select a line and it will scroll to the top of the page and I'll have to scroll back down. See video. 

![skipping23](https://user-images.githubusercontent.com/10658257/82759734-2eeec080-9dbd-11ea-9da0-04101d79453e.gif)

**Comment by inderpreetsingh** [comment]
We were able to reproduce it - this happens when you click on a verse that has already been once used.
