### ISSUE TITLE
Changelog should only auto-appear once per new release

### ISSUE THREAD

**Issue by plug-n-play** [KhalisFoundation/sttm-desktop#1108]
As of now, with the default setting, the Change logs appear every time the app starts. Instead, the change logs should only appear automatically when the app updates

**Comment by tsingh777** [comment]
There's a setting for this to "limit-changelog" we intentional make the user see the change log 5 time unless there's a new changelog. cc @maneetpaul

**Comment by maneetpaul** [comment]
Yes, this is intentional.
