### ISSUE TITLE
When you go to prev/next shabad through shabad pane, that shabad is not stored in history.

### ISSUE THREAD

**Issue by inderpreetsingh** [KhalisFoundation/sttm-desktop#1151]
I am not sure if we wanted that as a behaviour, but pointing out (just in case). When we change the Shabad from next previous icons in shabad pane, that history is not saved in history pane.

**Comment by Gauravjeetsingh** [comment]
Duplicate of https://github.com/KhalisFoundation/sttm-desktop/issues/1759

Closing this one.
