### ISSUE TITLE
Loading animation for Sync Code

### ISSUE THREAD

**Issue by maneetpaul** [KhalisFoundation/sttm-desktop#1161]
Sync Code doesn't appear unless I click on the icon for the Sync menu a second time. 

Need to add some sort of loading animation for the sync code while the api is fetching it and also ensure that the code appears without needing to close and reopen the modal.

**Comment by ManjotS** [comment]
you could make this safer by first hitting api.sikhitothemax.org/health and
if that is not ok: true then notify user service is unavailable. If it is
ok, then show loader while requesting code.
