### ISSUE TITLE
Bani Overlay display issues

### ISSUE THREAD

**Issue by saintsoldierx** [KhalisFoundation/sttm-desktop#1191]
![image](https://user-images.githubusercontent.com/27791330/91119885-3d14dd00-e649-11ea-9f9e-4ff912d6e79e.png)

Padding sides/top/bottom is way too much. Needs to be less (see yellow marks)
Padding-right of text is not correct - if long Bani line that splits into two lines, then it means there will be no padding to the right of it (see red marks)

**Comment by Gauravjeetsingh** [comment]
Fixed in latest, closing this out
