### ISSUE TITLE
Add greater range in font size customization

### ISSUE THREAD

**Issue by navdeepsinghkhalsa** [KhalisFoundation/sttm-desktop#12]
Add a few sizes higher and lower

**Comment by tarunsingh5** [comment]
@navdeepsinghkhalsa do you mind if we give this to @inderpreetsingh ?

**Comment by tarunsingh5** [comment]
@navdeepsinghkhalsa is this something you plan to do still?

**Comment by tarunsingh5** [comment]
@navdeepsinghkhalsa should we give this to @inderpreetsingh ?

**Comment by tarunsingh5** [comment]
@tsingh777 can you knock this one out - should be a quick fix

**Comment by tarunsingh5** [comment]
bump

**Comment by saintsoldierx** [comment]
I am going to close this - don't think this is an issue anymore.
