### ISSUE TITLE
Feature Request-Auto Scrolling In Akhand Path View

### ISSUE THREAD

**Issue by SukhmanpreetSingh** [KhalisFoundation/sttm-desktop#123]

**Comment by tarunsingh5** [comment]
i believe this is already there - right @navdeepsinghkhalsa

**Comment by navdeepsinghkhalsa** [comment]
I think they may be asking for the same kind of auto-scroll as Sundar Gutka. We're going to be releasing auto-advance soon

**Comment by SukhmanpreetSingh** [comment]
ji navdeep ji

**Comment by maneetpaul** [comment]
Being addressed in other issues.
