### ISSUE TITLE
Projector Border

### ISSUE THREAD

**Issue by ManjotS** [KhalisFoundation/sttm-desktop#1236]
<div> Freshdesk Ticket ID: <a href="https://khalis.freshdesk.com/a/tickets/2482">2482</a></div>
                       <div> Freshdesk Ticket Agent: Aman Singh</div>
                       <div> Freshdesk Ticket Agent Email: saintsoldierx@gmail.com</div>
                       <div> Ticket Priority: Medium</div>
                       <div> Freshdesk Ticket Description: </div><div dir="ltr">
<div>Hi, Is it possible to remove the Border around the screen when the presentation/Shabad is running.  We run our projector system on a wall (without a projector screen) and use a other borderless presentations.  Is there any way of removing the border please?</div>
</div>

**Comment by ManjotS** [comment]
<div>Agent Aman Singh linked Freshdesk ticket <a href="https://khalis.freshdesk.com/a/tickets/2482">2482</a> for this issue.</div>

**Comment by maneetpaul** [comment]
![WhatsApp Image 2020-11-01 at 18 03 57](https://user-images.githubusercontent.com/10658257/98970483-fc0cc600-24dd-11eb-9cad-7900af6351bf.jpeg)
![WhatsApp Image 2020-11-01 at 18 03 57 (3)](https://user-images.githubusercontent.com/10658257/98970493-fdd68980-24dd-11eb-8f7e-ee4f8291cf4a.jpeg)

**Comment by maneetpaul** [comment]
Fixed by #1246
