### ISSUE TITLE
Long Delay

### ISSUE THREAD

**Issue by SukhmanpreetSingh** [KhalisFoundation/sttm-desktop#124]
I'm experiencing great delay when selecting a new gurbani line to display since the update to version 3.3.1.
The delay reminds me to the times when sttm worked with powerpoint. Really makes it hard to use while keertan.

I'm running windows 7.

Please boost the performance back to level it used to be on previous version if possible ji.

**Comment by tarunsingh5** [comment]
duplicate of #113
