### ISSUE TITLE
preview (and full slide) taking second monitor size and shape

### ISSUE THREAD

**Issue by ManjotS** [KhalisFoundation/sttm-desktop#125]
If I have 2 monitors with second monitor turned to portrait, even if I leave presenter mode, the slides are skinny in the shape of a portrait monitor

**Comment by tarunsingh5** [comment]
you can resize them by dragging them

**Comment by maneetpaul** [comment]
Closing for now for the sake of cleaning up. Will address in the future as needed.

**Comment by tarunsingh5** [comment]
closing after slack discussion w/ @ManjotS
