### ISSUE TITLE
V8.2 Macos - "Verify Daily Hukamnama is accurate" however Daily Hukamnama didn’t load. 

### ISSUE THREAD

**Issue by djsingh1** [KhalisFoundation/sttm-desktop#1270]
When I clicked on the Daily Hukamnama, it didn't load. Just to ensure my desktop app was working, I clicked on Show Random Shabad and it did. I then clicked on Daily Hukamnama and it again did not load. I then clicked on Whats New and that did load.

**Comment by Gauravjeetsingh** [comment]
Working fine from desktop now, only issue with hukamnama not updating in API, closing this out here.
