### ISSUE TITLE
Add romanized gurmukhi search (may be with phonetic)

### ISSUE THREAD

**Issue by inderpreetsingh** [KhalisFoundation/sttm-desktop#128]
Romanized Gurmukhi can have different spellings for different people. If we use `Soundex` (or similar algorithms) we can solve that problem. There has been some discussion with @ManjotS about this, but I think it would require changes to database structure. We will have to add phonetic codes. 
OR
we can just imitate the one that's on website.

**Comment by ManjotS** [comment]
We implemented on web using mariadb soundex function:

http://dev.sikhitothemax.org/

**Comment by bickyb** [comment]
I agree with Interpreet that sometimes people spell things different ways.
For example, I searched for the shared 'Bin Boleya Sabh Kich Janda'. The search yielded no results.
Apparently I needed to search for 'Vin Boleya Sabh Kich'

Punjabi is my second language so I was unaware that the shabad actually starts with a 'Vava' and not a 'Buba'.  

If we have the first letter search functionality, then we could have a mapping for V or B equals bubba or vava.

I personally think searching by the entire romanized Gurmukhi words is not needed and more of what is needed is the first letter romanized Gurmukhi search.

**Comment by ManjotS** [comment]
@maneetpaul this is a new search feature we have multiple user requests for for all products. Some people cant  read gurmukhi  and just want to put in "t" for tanka, tata, thatha etc etc.. We had this feature accidentally but "fixed" it with making romanized more accurate with soundex. Had a few complains.

Romanized first letter is needed.

**Comment by Gauravjeetsingh** [comment]
We have romainzed english first letter search in latest release, closing this out.
