### ISSUE TITLE
8.3 Alpha - Rename App Layout to App Settings

### ISSUE THREAD

**Issue by maneetpaul** [KhalisFoundation/sttm-desktop#1284]
The heading for the last section of the settings currently says App Layout. Let's change that to App Settings for consistency

**Comment by Gauravjeetsingh** [comment]
This seems to be fixed in dev branch already. It's safe to close this issue @maneetpaul veerji!

**Comment by Gauravjeetsingh** [comment]
Update: Found the missing App Layout heading, opened a PR #1287
