### ISSUE TITLE
Search via Romanized First Letters

### ISSUE THREAD

**Issue by bickyb** [KhalisFoundation/sttm-desktop#129]
Say for example you want to search for the shabad Jo Mange Thakur Apne Thay. You would need to know the exact spelling of the romanized shabad to be able to find it. What would be more effective is if we can search for the first letters: jmtat . This is the functionality that was available in sikhitothemax the original . Also, we need the ability to search phonetically. So say for example I am searching for the shabad Kar Kirpa Prabh Dheen Dhayala. Then I should be able to search for either ‘KKPDD’ or ‘CCPTT’ as these are phonetically close in English. This was doable in the original sikhitothemax. Please let me know if you have any questions and I can walk you through the needed functionality on a phone call if needed.

**Comment by tsingh777** [comment]
Got another request for this feature from sevadaars at the South Florida Gurdwara. 

cc. @maneetpaul

**Comment by bickyb** [comment]
Hi, I wanted to see if there has been any progress with this feature.    We have a number of Gurdwaras in the DFW area that are still using the old version of SikhitotheMax (which is years old) because of the lack of this feature to search phonetically.  This is extremely critical for those who are not as fluent with Gurmukhi.

**Comment by maneetpaul** [comment]
@bickyb - Thank you for the follow-up - we will work on prioritizing this!

**Comment by Gauravjeetsingh** [comment]
Working in latest release, closing this out.
