### ISSUE TITLE
not able to clone submodule

### ISSUE THREAD

**Issue by sukhpalsingh** [KhalisFoundation/sttm-desktop#13]
I am trying to install locally and getting the following error:

Cloning into 'C:/Users/Sukhpal/Projects/sttm-desktop/www/core'...
Host key verification failed.
fatal: Could not read from remote repository.

Can you please guide me what to do in this case?

I am using windows.

**Comment by taranjs** [comment]
See if this helps:
https://askubuntu.com/questions/45679/ssh-connection-problem-with-host-key-verification-failed-error
https://stackoverflow.com/questions/13509293/git-fatal-could-not-read-from-remote-repository

**Comment by sukhpalsingh** [comment]
Thanks for the help. It leads to me to the following to fix this issue:

1. Generate ssh key
https://help.github.com/articles/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent/

2. Attach the generated ssh key to the github account
https://help.github.com/articles/adding-a-new-ssh-key-to-your-github-account/

3. Use git bash (for windows) to perform the clone because git bash uses ssh keys.
