### ISSUE TITLE
Add ability to show multiple shabads in the navigator pane 

### ISSUE THREAD

**Issue by maneetpaul** [KhalisFoundation/sttm-desktop#1314]

**Comment by prebhdevsingh** [comment]
@maneetpaul can you share a wireframe of how this may look like? a quick sketch will be helpful.

**Comment by Gauravjeetsingh** [comment]
@maneetpaul / @saintsoldierx veerjis, is this the same feature we recently did, the multipane workspace?

#1927

**Comment by saintsoldierx** [comment]
Yes, I think this can be closed.
