### ISSUE TITLE
Ceremonies like Anand kaaraj doesn't show the english slides

### ISSUE THREAD

**Issue by Gauravjeetsingh** [KhalisFoundation/sttm-desktop#1318]
![Peek 2021-03-02 13-22](https://user-images.githubusercontent.com/1990932/109615831-6a8f9580-7b5a-11eb-91a7-213a0b689056.gif)

Bani controller also shows empty lines, but that would require some change in web code and not from desktop side. I will add issue for that in sttm-web repo.

**Comment by tsingh777** [comment]
Looks like this is due to having translations set to hindi.

**Comment by Gauravjeetsingh** [comment]
Yes correct, if I set translation back to english, it works
