### ISSUE TITLE
Hackathon Block# 2 - Complete new auto-update method (w/ msging) .. shortcuts

### ISSUE THREAD

**Issue by prebhdevsingh** [KhalisFoundation/sttm-desktop#133]
STTMv4 to be released independently. We will market latest version in person and social media. We can eventually figure out what to do with old version.

**Comment by tarunsingh5** [comment]
need to test pushing a message @navdeepsinghkhalsa @ManjotS

**Comment by tarunsingh5** [comment]
confirming test worked @ManjotS

**Comment by ManjotS** [comment]
deleting it
