### ISSUE TITLE
Darker themes make the search results hard to read

### ISSUE THREAD

**Issue by saintsoldierx** [KhalisFoundation/sttm-desktop#1333]
The gray in the unhighlighted words are very hard to read. Make it lighter.

![image](https://user-images.githubusercontent.com/27791330/113487271-02d7ad80-946c-11eb-946c-977726fd6bc0.png)

**Comment by Gauravjeetsingh** [comment]
Tested it both on linux and mac, unable to get as dark colored text as shown in above image.

This is the screenshot from dev branch in Mac with same theme Darbar Blue.

![Screenshot 2021-04-06 at 12 55 01 PM](https://user-images.githubusercontent.com/1990932/113674590-fbb4d780-96d7-11eb-8b1e-5fecc224576c.png)

**Comment by Gauravjeetsingh** [comment]
Tested it after creating a build from dev branch as well, got same output as above. I can still open a PR with a lighter non highlight color compared to current one.

**Comment by saintsoldierx** [comment]
Strangely enough, I am also now unable to reproduce this. Weird. Can close for now.
