### ISSUE TITLE
Bug: Can't move SikhiToTheMax Windows, can only resize (BigSur11.5.1, STTM version 8.3.1)

### ISSUE THREAD

**Issue by savraj** [KhalisFoundation/sttm-desktop#1352]
I'm on Mac OS X Big Sur 11.5.1

Opening STTM Desktop 8.3.1 I can resize the window, but can't move it -- like grab the top bar of the window and move it to a different location on screen. Very odd.  This is true for both the SikhiToTheMax window and the SikhiToTheMax Viewer window.

Is this intentional? It was awesome to be able to run Sikhi to the max with movable windows, just like any other app.

I'm worried that it might be just on my machine because I can't imagine you guys developing this app and not seeing this bug.  I can provide a video if you can't immediately reproduce.

**Comment by Gauravjeetsingh** [comment]
It should be working now, closing this out
