### ISSUE TITLE
9.0 Verse list component issue

### ISSUE THREAD

**Issue by MySmilingTurban** [KhalisFoundation/sttm-desktop#1364]
In the Shabad pane, from where we navigate through verses of a Shabad.
The last line is not visible.
![image](https://user-images.githubusercontent.com/51584037/137488540-322b94c6-b7e8-49a5-a665-3fcb6abdfd0c.png)

**Steps to replicate**
Search 'sksl' and select ਸਾਧ ਕੈ ਸੰਗਿ ਲਗੈ ਪ੍ਰਭੁ ਮੀਠਾ ।।
Navigate to the last verse of the Shabad,
It isn't visible in the verse list

**Comment by inderpreetsingh** [comment]
Issue is fixed and code is merged. Closing the issue.
