### ISSUE TITLE
9.0 Anand Sahib(Bhog) shortcut doesn't allow to switch to Shabad in History

### ISSUE THREAD

**Issue by MySmilingTurban** [KhalisFoundation/sttm-desktop#1365]
**Steps to replicate**
- Search any Shabad
- Use Anand Sahib (Bhog) shortcut (Ctrl+4)
- Try to switch to any Shabad from History

It doesn't open up

**Comment by inderpreetsingh** [comment]
Issue is fixed and code is merged. Closing the issue.
