### ISSUE TITLE
9.0 Shabad pane Autoscroll does not work

### ISSUE THREAD

**Issue by MySmilingTurban** [KhalisFoundation/sttm-desktop#1370]
Navigating through lines on the Shabad pane does not automatically scroll the verse list to desired verse.
Happening in both presenter and single display mode.

**Comment by MySmilingTurban** [comment]
Issue persists in the latest build
Same issue is coming up in Akhand Paath View, the display doesn't scroll along with verse navigation in verse pane.

**Comment by MySmilingTurban** [comment]
@inderpreetsingh @Gauravjeetsingh 
Auto-scroll working in Akhand Paath View. Thanks for the commendable efforts.

But the verses in shabad pane are not scroll with navigation, they used to in last stable build
![image](https://user-images.githubusercontent.com/51584037/142692557-c4acdfca-f7b8-41a6-913d-9648e95308f9.png)
(the shabad pane)

**Comment by Gauravjeetsingh** [comment]
Fixed in dev, closing this out
