### ISSUE TITLE
Error while using npm install in root

### ISSUE THREAD

**Issue by MySmilingTurban** [KhalisFoundation/sttm-desktop#1372]
Executed npm install in the cloned repo root, and all these error messages came up

$ npm install
npm ERR! code 1
npm ERR! path C:\Users\Gurmehar Singh\Desktop\sttm\sttm-desktop\node_modules\node-sass
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node-gyp rebuild
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@3.8.0
npm ERR! gyp info using node@16.2.0 | win32 | x64
npm ERR! gyp ERR! configure error
npm ERR! gyp ERR! stack Error: Command failed: C:\Program Files\Python38\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
npm ERR! gyp ERR! stack   File "<string>", line 1
npm ERR! gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
npm ERR! gyp ERR! stack                       ^
npm ERR! gyp ERR! stack SyntaxError: invalid syntax
npm ERR! gyp ERR! stack
npm ERR! gyp ERR! stack     at ChildProcess.exithandler (node:child_process:326:12)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:365:28)
npm ERR! gyp ERR! stack     at maybeClose (node:internal/child_process:1067:16)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
npm ERR! gyp ERR! System Windows_NT 10.0.19043
npm ERR! gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Gurmehar Singh\\Desktop\\sttm\\sttm-desktop\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd C:\Users\Gurmehar Singh\Desktop\sttm\sttm-desktop\node_modules\node-sass
npm ERR! gyp ERR! node -v v16.2.0
npm ERR! gyp ERR! node-gyp -v v3.8.0
npm ERR! gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Gurmehar Singh\AppData\Local\npm-cache\_logs\2021-10-20T13_35_51_889Z-debug.log

What to do?
PS: I am new to npm, so unable to resolve it

**Comment by Gauravjeetsingh** [comment]
Hey @MySmilingTurban yeah, we have been having this issue while setting up dev environment on windows machine. 
This is a dev issue, and doens't go to users, so was on a lower priority, as current devs were either using linux or mac.

But if you can find a solution for setting it up on windows, that'd be great. We do come across testing issues on windows, because only way to test is by creating a build on linux machine, and then installing on windows which is time consuming.

**Comment by Gauravjeetsingh** [comment]
This is fixed now. Closing this out
