### ISSUE TITLE
9.0 Few shortcuts not working

### ISSUE THREAD

**Issue by MySmilingTurban** [KhalisFoundation/sttm-desktop#1373]
Ctrl + 5/6/G aren't providing the intented response

Intented shortcuts
Ctrl + 5 - Help Menu
Ctrl + 6 - Shortcut Legend
Ctrl + G - Insert Slide

**Comment by MySmilingTurban** [comment]
@inderpreetsingh @Gauravjeetsingh 
All shortcuts are working now in presentation mode
But in single display mode, only Ctrl + 5/6/G are working else are not.

**Comment by Gauravjeetsingh** [comment]
Fixed in dev, closing this out

**Comment by MySmilingTurban** [comment]
Shortcuts not working in **Mac build**
@Gauravjeetsingh @inderpreetsingh
