### ISSUE TITLE
[Hackathon]Chromecast bug 

### ISSUE THREAD

**Issue by tsingh777** [KhalisFoundation/sttm-desktop#138]
In the chromecast branch, when the app is casting, when the chromecast is taken over by another person, the app does not get an event to stop casting. Does not cause any usage issues but an error popup comes up. 

<IMAGE to be added>

**Comment by tarunsingh5** [comment]
was this fixed?

**Comment by tarunsingh5** [comment]
bump - is this still an issue?

**Comment by tarunsingh5** [comment]
was this ever fixed?

**Comment by tsingh777** [comment]
Not yet. Its an edge case so not a severe bug.

**Comment by maneetpaul** [comment]
Closing, this is an edge case that has never been reported.
