### ISSUE TITLE
9.0 Random and Hukam in History shows up as O

### ISSUE THREAD

**Issue by MySmilingTurban** [KhalisFoundation/sttm-desktop#1381]
When using random or hukam, history notes the action but displays it as O
it gives expected result when clicked

![image](https://user-images.githubusercontent.com/51584037/142694219-4a309b15-1b6d-4cf3-be82-d8ff175582b6.png)

**Comment by Gauravjeetsingh** [comment]
Unable to reproduce in code. I am able to get this in the alpha build. But if I run it on my local system, it works fine. I also created a build manually and tested on windows, it still worked fine. I think there has been some issue while creating that alpha build, this would be fixed when we create another alpha build. If not, I will look more into it.

**Comment by MySmilingTurban** [comment]
@inderpreetsingh @Gauravjeetsingh 
Same issue occurring in mac build also

**Comment by MySmilingTurban** [comment]
@inderpreetsingh @Gauravjeetsingh Veerjis,
The issue is partially resolved 👍🏽 

In both Windows and Mac build,
- Hukam still displays as O
- Random Shabad is showing as expected

**Comment by MySmilingTurban** [comment]
@Gauravjeetsingh @inderpreetsingh veerjis,
Encountered the following issues in history tab,
- The History tab again shows shabads from random and hukam as O
- Also, in both modes, the bottom margin is elevated _(Note - the screenshots were taken with history scrolled to the utmost bottom)_, it gets corrected when we open and close the shortcuts
![image](https://user-images.githubusercontent.com/51584037/151200881-c36c4cfd-2228-4cc3-b1ef-6a60729c3fb4.png)
![image](https://user-images.githubusercontent.com/51584037/151201247-e66d11f8-6b34-4742-9e38-cd6272d2451a.png)
