### ISSUE TITLE
9.0 Sangat Sync and Bani Controller

### ISSUE THREAD

**Issue by MySmilingTurban** [KhalisFoundation/sttm-desktop#1383]
- Sangat Sync is not connecting and prompting invalid code.
- Bani Controller keeps loading and loading but isn't connecting

**Comment by Gauravjeetsingh** [comment]
@MySmilingTurban just checked, that's a issue on web side. Currently both sttm-web prod and stg are using the prod API.

Sttm-desktop uses the dev api in alpha release, but sttm-web is using prod API. And we can't connect dev api desktop with prod API web.

I will open a ticket for this in that repo, and see if this can be fixed early on for QAing 9.0 release

**Comment by Gauravjeetsingh** [comment]
https://github.com/KhalisFoundation/sttm-web/issues/1481

**Comment by MySmilingTurban** [comment]
@Gauravjeetsingh @inderpreetsingh 
Sync and controller works in Win but not in Mac
Issue persists in Mac Build
