### ISSUE TITLE
Remote Control

### ISSUE THREAD

**Issue by prebhdevsingh** [KhalisFoundation/sttm-desktop#140]

**Comment by maneetpaul** [comment]
Closing for now for the sake of cleaning up. Will address in the future.

**Comment by ManjotS** [comment]
This feature is defined as:
- Add remote admin sync code (sttm api feature https://github.com/KhalisFoundation/sttm-api/issues/3)

- Add ability within app to remote  admin another screen  using the remote admin sync code (most likely in lower right presenter screen, separate pane for single screen) 

- Flow: user opens remote sync and selects server or client (similar to synergy2, teamviewer, vnc), user clicks server, they are provided the 6 digit admin sync code. User then selects client on another machine, enters  code, clicks start. Everything done on client is mirrored on server. This is done by sending line id to sttm-api which is pushed to server.

**Comment by ManjotS** [comment]
@navdeepsinghkhalsa as dev architect please comment on above
