### ISSUE TITLE
Padding issue in Single Display Mode on windows

### ISSUE THREAD

**Issue by inderpreetsingh** [KhalisFoundation/sttm-desktop#1405]
Due to the additional title bar in windows, the content on the viewer is getting hidden.

Steps to reproduce:
- Go to single display mode
- Search any Shabad. Eg: `ddeh`
- You will see some part of the viewer is covered from the top.

Suggested solution:
- Add extra padding on top when it's on windows

![image](https://user-images.githubusercontent.com/1131610/149316995-ca71b0ec-2d24-4706-abb6-7aa853a70dbd.png)

**Comment by theamanjs** [comment]
@inderpreetsingh veerji can I work on this one?

**Comment by inderpreetsingh** [comment]
Sure @theamanjs please go ahead :slightly_smiling_face:

**Comment by inderpreetsingh** [comment]
@theamanjs I forgot to mention please send PR to `9.0-fix` branch instead of dev for this PR.

**Comment by theamanjs** [comment]
Sure veerji
