### ISSUE TITLE
Surface Sundar Gutka Compiled Banis

### ISSUE THREAD

**Issue by prebhdevsingh** [KhalisFoundation/sttm-desktop#141]

**Comment by maneetpaul** [comment]
Adding this to 4.2 milestones. Ideally all compiled banis from Sundar Gutka should be surfaced, however, we should prioritize 6 Pauri Anand Sahib and ADV

**Comment by ManjotS** [comment]
@maneetpaul we may need to spin up a ticket for 6 pauree anand sahib in banidb as its not currently there

**Comment by ManjotS** [comment]
6 pauree anand sahib added as Bani ID 1000 .

Bani IDs 1000-2000 are now dedicated to STTM specific banis.

**Comment by maneetpaul** [comment]
I am going to divide these into separate tickets.
