### ISSUE TITLE
Highlight settings button

### ISSUE THREAD

**Issue by saintsoldierx** [KhalisFoundation/sttm-desktop#1419]
- Include a :hover over buttons at top.
- If button is selected, have it highlight.
- As user scrolls, would be nice to have the buttons automatically depending on which section they are in.

![image](https://user-images.githubusercontent.com/27791330/152700664-41e23d8f-50f7-46ef-8000-bc9ad409d426.png)

**Comment by theamanjs** [comment]
@saintsoldierx Veerji, here are two versions with the preview label. Please let me know which should I finalize?

Case 1: Preview on top with text center
![](https://cdn.discordapp.com/attachments/640132531517128754/941372354318188575/unknown.png)

Case 2: Preview at bottom with text center
![](https://cdn.discordapp.com/attachments/640132531517128754/941372094401359942/unknown.png)

**Comment by saintsoldierx** [comment]
At top, left align text

**Comment by theamanjs** [comment]
This is creating UI issue in dark mode. I'll look into this.
