### ISSUE TITLE
Improvements to filter

### ISSUE THREAD

**Issue by saintsoldierx** [KhalisFoundation/sttm-desktop#1423]
- If I search for a result, the source, writer and raags should not show any option if results are not null. For example, if I enter a search term and no results match Sri Guru Arjan Dev Jee, then that Guru Sahib should not appear in the drop down for filter. 
- Please remove capital S in search where it says "Enter Search term...".
- Remove shadow of the search bar, make it clean.
- Selecting all the search options (first letter, full word etc) doesn't work properly. Should you only be able to select one? If i enter in some letters and change the search option, it should run the search again ideally. Needs improvement.

**Comment by Gauravjeetsingh** [comment]
@saintsoldierx veerji, done all the above, except the dropdown filters, need to think a little more into how would that work with current search logic.

**Comment by theamanjs** [comment]
@Gauravjeetsingh as this one is already merged. Should I close this one too?
