### ISSUE TITLE
Spacebar short cut to go to next unseen line not working.

### ISSUE THREAD

**Issue by Gauravjeetsingh** [KhalisFoundation/sttm-desktop#1446]

**Comment by Gauravjeetsingh** [comment]
@theamanjs can u take a look at this, pressing space should go to the next line in opened shabad

**Comment by theamanjs** [comment]
Sure veerji, on it.

**Comment by theamanjs** [comment]
> @theamanjs can u take a look at this, pressing space should go to the next line in opened shabad

@Gauravjeetsingh veerji, I was checking this in v8.4, and pressing spacebar is going to home verse. Are you sure we are looking to bound the spacebar shortcut with next line?
