### ISSUE TITLE
Change checkbox color on dark theme

### ISSUE THREAD

**Issue by Gauravjeetsingh** [KhalisFoundation/sttm-desktop#1448]
Checkboxes on dark themes are hard to see.

**Comment by theamanjs** [comment]
@Gauravjeetsingh do we need design input from anyone particularly? Though, I made a little change locally which you can see below. How about this one?

![image](https://user-images.githubusercontent.com/38748298/156047436-3674a90b-47d1-485c-8ccc-b01f42d1e4a7.png)

**Comment by saintsoldierx** [comment]
I think looks good personally

**Comment by theamanjs** [comment]
I will work on this one as well :raised_hands:
