### ISSUE TITLE
9.0 - Single Display Issue

### ISSUE THREAD

**Issue by MySmilingTurban** [KhalisFoundation/sttm-desktop#1469]
## (Major Issue in Windows and Mac)
When you open a shabad and minimise the side pane, it becomes unaccessible leaving no way to access any settings or other mode.

**Video Reference:**
https://user-images.githubusercontent.com/51584037/156739672-3a8d1f69-f12b-4aed-b2a9-b824b80741a1.mp4

**Steps to reproduce:**
- open single display mode
- search and open a shabad
- minimise the bottom side pane
- navigate through shabad
- you'll see that there's no way back to normal, only you can scroll through the shabad

**Comment by theamanjs** [comment]
I found one more issue while I was reproducing this one. 

![single display issue](https://user-images.githubusercontent.com/38748298/156996828-b9105f05-5aab-4e3c-9dc4-3d136d95bd53.gif)

**Comment by MySmilingTurban** [comment]
Thanks veerji, this sort of issue came earlier too
Thanks for reporting

**Comment by theamanjs** [comment]
Fixed this one too

**Comment by MySmilingTurban** [comment]
Thanks for the commendable fixes
