### ISSUE TITLE
9.0 - Mac history scroll margin issue

### ISSUE THREAD

**Issue by MySmilingTurban** [KhalisFoundation/sttm-desktop#1471]
Bottom margin is high on start, but when you maximise and minimise shortcut tray, it gets fixed.

**Image for reference:**
![image](https://user-images.githubusercontent.com/51584037/156741218-6bf5b682-3add-4f63-b494-e0593b0c0501.png)

**Steps to reproduce:**
- Open sttmd on mac
- search for a few shabads
- look history tab, you'll notice the bottom margin is elevated

**Comment by theamanjs** [comment]
@Gauravjeetsingh veerji, please check this issue. I don't have access to mac.
