### ISSUE TITLE
Spacing issue in Bani and Translation in Bani Overlay 

### ISSUE THREAD

**Issue by theamanjs** [KhalisFoundation/sttm-desktop#1493]
There is a bigger space between Bani and Translation in Bani Overlay Mode. No option to hide Translation.

![image](https://user-images.githubusercontent.com/38748298/159278293-fd81daff-2148-41e2-87e2-a4f939d5bdbd.png)

**Comment by Gauravjeetsingh** [comment]
This is fixed in latest release, closing this out
