### ISSUE TITLE
9.0beta History tab bottom margin in Single Display Mode

### ISSUE THREAD

**Issue by MySmilingTurban** [KhalisFoundation/sttm-desktop#1503]
In Single Display mode, the bottom margin of the history tab is uplifted
![image (3)](https://user-images.githubusercontent.com/51584037/160106958-852b3d47-ffae-479b-bbce-e99fe65113be.png)

**Steps to reproduce:**
1. Open Single Display Mode
2. Open a few shabads at random
3. Go to history tab, notice the uplifted bottom margin

**Comment by MySmilingTurban** [comment]
I think I know, why it's happening

When you have the shortcut tray open in presentation mode, it elevates the bottom margin in single display mode.
@Gauravjeetsingh @theamanjs

**Comment by theamanjs** [comment]
@MySmilingTurban thanks for reporting with detail. I'll fix this one today.
