### ISSUE TITLE
Win - History not stored when using next bani

### ISSUE THREAD

**Issue by MySmilingTurban** [KhalisFoundation/sttm-desktop#1526]
https://user-images.githubusercontent.com/51584037/162215142-81bdae81-2b55-40f6-8acd-a77cb2e7bdce.mp4

Steps to reproduce:
1. Search any shabad
2. Navigate to the immediate next shabad using next button
3. Notice that it gets registered in History as O

**Comment by MySmilingTurban** [comment]
The history tab is not storing Baanis opened using next baani (for more info, refer upper video).
(Refer to video ^^)
Steps to reproduce:

1. Search any shabad.
2. Navigate to the immediate next shabad using next button.
3. Notice it doesn't get stored in history.

**Comment by theamanjs** [comment]
@MySmilingTurban veerji, this is an expected thing from the 8.1.0 release. Firstly it was showing O that you reported earlier. I copied the behavior of 8.1.0 which was not showing anything. 

Video of 8.1.0 version
![history with arrow keys](https://user-images.githubusercontent.com/38748298/165042698-a7aa6f86-8e91-45ff-be8b-0c84b0313901.gif)

**Comment by MySmilingTurban** [comment]
Okay @theamanjs Veerji,
I thought storing it in history would be beneficial for users.
