### ISSUE TITLE
Mac  - “Install and restart” button on popup does not work on Mac

### ISSUE THREAD

**Issue by prebhdevsingh** [KhalisFoundation/sttm-desktop#1539]
“Install and restart” button on popup does not work on Mac. Didnt work on beta either. Can go manually into context menu and select install and restart and it works but that popup doesn’t.

**Comment by MySmilingTurban** [comment]
@theamanjs @prebhdevsingh veerjis, 
Same issue in Windows version as well

**Comment by theamanjs** [comment]
@MySmilingTurban veerji, can you check on the latest production release (9.1.2) if this issue still persists?

**Comment by Gauravjeetsingh** [comment]
This has been pushed to production, closing this out.
