### ISSUE TITLE
Toggle display screen on and off

### ISSUE THREAD

**Issue by saintsoldierx** [KhalisFoundation/sttm-desktop#155]
I should be able to "end shabad" or have an easy one-click way to toggle the presentation window on and off to reveal the desktop background. At the moment users are closing the entire application between shabads to hide the window.

**Comment by inderpreetsingh** [comment]
I am thinking we should not add any new option in display options as of current UI - may be fix that in 5.0 with new UI overhaul?

Thank you!

**Comment by maneetpaul** [comment]
Duplicate of #245
