### ISSUE TITLE
Formatting issue with announcements

### ISSUE THREAD

**Issue by saintsoldierx** [KhalisFoundation/sttm-desktop#1554]
The onscreen display should take into account the formatting done in the announcement text box eg. line breaks.

<img width="699" alt="image" src="https://user-images.githubusercontent.com/27791330/166159261-4654d522-ac71-4253-bb10-aebebd554a75.png">

**Comment by Gauravjeetsingh** [comment]
@yadvirkaur can you see if this issue still exists in latest dev branch. If it exists, can you please fix this as well.

**Comment by yadvirkaur** [comment]
This issue doesn't exist,  it was taken care of with the help of CSS property: `white-space: pre;`. But this property is creating an issue with the Mool Mantr slide whose text doesn't wrap in Single Display mode as a result of the above property. This can be solved with: `white-space: pre-wrap;` as on [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/white-space).

https://github.com/KhalisFoundation/sttm-desktop/assets/4669545/57457769-cf5e-4d80-9c7f-dcbb9013892c
