### ISSUE TITLE
Home line not getting auto assigned

### ISSUE THREAD

**Issue by saintsoldierx** [KhalisFoundation/sttm-desktop#1556]
In the line navigator, the home line is no longer getting assigned when a user opens a shabad.

<img width="691" alt="image" src="https://user-images.githubusercontent.com/27791330/166159349-971617b4-477f-416c-9141-fb8326adb7f2.png">

**Comment by Gauravjeetsingh** [comment]
This was fixed in 9.1.2 release, closing this out
