### ISSUE TITLE
Make highlighted text heavier

### ISSUE THREAD

**Issue by saintsoldierx** [KhalisFoundation/sttm-desktop#1566]
Cannot really tell easily between the highlighted text when using search. I would suggest to make the highlighted text more heavy/bold. It's not too bad in light mode but dark mode is much more tougher to differentiate.

<img width="708" alt="image" src="https://user-images.githubusercontent.com/27791330/167089068-be746787-dc02-44bc-a9ee-7f1457ba1c93.png">

<img width="687" alt="image" src="https://user-images.githubusercontent.com/27791330/167089249-74f7b29c-8ebe-489d-ae8c-99f1df8daa36.png">

**Comment by theamanjs** [comment]
This got reported on slack again on dark mode. Will be working on this in upcoming releases. Message link: https://khalis.slack.com/archives/CFS6E54PN/p1663306180980609
