### ISSUE TITLE
Dropdown should be on icon and text

### ISSUE THREAD

**Issue by saintsoldierx** [KhalisFoundation/sttm-desktop#1567]
At the moment, when you click on a filter, you have to click on the triangle icon to use the dropdown. The dropdown should work when you click the icon OR the text next to it as highlighted in the graphic below.

<img width="317" alt="image" src="https://user-images.githubusercontent.com/27791330/167089484-3aa43205-bd63-4e27-8059-76b28d9fb91b.png">

**Comment by Gauravjeetsingh** [comment]
This is fixed in latest release, closing this out
