### ISSUE TITLE
Search is slow

### ISSUE THREAD

**Issue by saintsoldierx** [KhalisFoundation/sttm-desktop#1573]
Searching is slower than previous versions of STTM. Could we look into what is causing this issue? If the issue is related to the extra metadata we are showing such as ang, writer etc, then let's look at having a setting to hide or show this extra info or find a way to speed up the search.

**Comment by Gauravjeetsingh** [comment]
@saintsoldierx veerji, any specific search query or shabad where you experienced this slowness?

**Comment by saintsoldierx** [comment]
No specific shabad, just generally it is slower. Few users also gave this
feedback

**Comment by theamanjs** [comment]
Veerji, are we still getting this issue?

**Comment by Gauravjeetsingh** [comment]
Closing this out for now, if we still had slow search issues, can re-open.
