### ISSUE TITLE
Filter is not obvious when activated

### ISSUE THREAD

**Issue by saintsoldierx** [KhalisFoundation/sttm-desktop#1574]
There is no way to know a filter is applied unless you click dropdown. We need to show a tab when filter is applied with an easy way to remove it without using dropdown.

<img width="693" alt="image" src="https://user-images.githubusercontent.com/27791330/167284851-208cb141-f585-4522-b2a7-ca40a631a0d9.png">

**Comment by Gauravjeetsingh** [comment]
Closing this out, as its released to prod.
