### ISSUE TITLE
:github: Vishraams are broken When it's show next lineThe vishraams on the bottom line are wrong They switch to being correct when that line becomes the main line

### ISSUE THREAD

**Issue by saintsoldierx** [KhalisFoundation/sttm-desktop#1580]
(Auto generated from slack)
:github: Vishraams are broken When it's show next lineThe vishraams on the bottom line are wrong They switch to being correct when that line becomes the main line
https://khalis.slack.com/archives/CFS6E54PN/p1652252175884229?thread_ts=1652252175.884229&cid=CFS6E54PN

**Comment by Gauravjeetsingh** [comment]
fixed by #1582

**Comment by Gauravjeetsingh** [comment]
Closing this out, as its released to prod.
