### ISSUE TITLE
Shortcut Tray Opening/Closing is causing App Crash

### ISSUE THREAD

**Issue by MySmilingTurban** [KhalisFoundation/sttm-desktop#1596]
**OS: Windows 10 & macOS**

Steps to reproduce:
1. Open/Close Shortcut Tray in History pane -> App Crash.

**Comment by theamanjs** [comment]
I was not able to reproduce this issue. @Gauravjeetsingh veerji can you try this one?

**Comment by Gauravjeetsingh** [comment]
Looking into it ji!

**Comment by Gauravjeetsingh** [comment]
I tested it 4-5 times on windows machine, and was unable to reproduce as well.

@MySmilingTurban ji, can you check if this is still an issue, or if there's certain edge case when this happens.

**Comment by MySmilingTurban** [comment]
Resolved in latest build
