### ISSUE TITLE
Bani controller cannot navigate through Sunder Gutka Banis

### ISSUE THREAD

**Issue by MySmilingTurban** [KhalisFoundation/sttm-desktop#1613]
OS: Win & macOS

Steps to reproduce:
1. Connect and use Bani Controller
2. Open any Bani from All Banis
3. Try to navigate, it doesn't

**Comment by Gauravjeetsingh** [comment]
@MySmilingTurban unable to reproduce, it's working fine for me now, tested with japji sahib on linux and windows.

Maybe when you tested, the sttm API wasn't working properly, can you please check again, also before testing, open the api health endpoint to make sure its working fine. 
https://api.sikhitothemax.org/health

**Comment by Gauravjeetsingh** [comment]
![sttm-bani](https://user-images.githubusercontent.com/1990932/179733147-5e0b00fe-0d0b-4f74-94a0-76e6f0500497.gif)

**Comment by Gauravjeetsingh** [comment]
Ah! got it. I will look into that. Thanks!

**Comment by theamanjs** [comment]
@Gauravjeetsingh were you able to reproduce this now? Can the label on this issue be changed?
