### ISSUE TITLE
Make viewer compatible to rpi

### ISSUE THREAD

**Issue by inderpreetsingh** [KhalisFoundation/sttm-desktop#1617]

**Comment by Gauravjeetsingh** [comment]
Update: Was able to get the viewer work with BrowserView functionality.

For a full support, need to fix the

- [ ] Move the viewer BrowserView behind the main app
- [ ] Increase the size of viewer on single display mode.

**Comment by Gauravjeetsingh** [comment]
This was completed and is in exisitng RPi PR.

**Comment by Gauravjeetsingh** [comment]
We were able to do this without switching to browser videw, closing this out.
