### ISSUE TITLE
Would it be possible to update OBS when the Vaahiguroo slide or other non-Panktee slides are selected?

### ISSUE THREAD

**Issue by saintsoldierx** [KhalisFoundation/sttm-desktop#1626]
(Auto generated from slack)
Would it be possible to update OBS when the Vaahiguroo slide or other non-Panktee slides are selected?
https://khalis.slack.com/archives/CFS6E54PN/p1658115691739659

**Comment by Gauravjeetsingh** [comment]
Duplicate of #1615 closing this out
