### ISSUE TITLE
English menu in Sundar Gutka screen

### ISSUE THREAD

**Issue by saintsoldierx** [KhalisFoundation/sttm-desktop#1639]
Provide a way to switch Gurmukhi in Sundar Gutka to English. A switch at the top in the title bar should suffice. This should switch all Banis and boxes in SG Baanis to English. 

<img width="1005" alt="image" src="https://user-images.githubusercontent.com/27791330/186002563-60922494-52cf-4c49-abb5-440e4e84b7b0.png">

**Comment by Gauravjeetsingh** [comment]
This has been pushed to production, closing this out.
