### ISSUE TITLE
Indicate database download

### ISSUE THREAD

**Issue by navdeepsinghkhalsa** [KhalisFoundation/sttm-desktop#164]
Currently message only shows up in search field on initial database download.

When a new DB is pulled, only a progress bar is shown, which may be confusing. Should show same or alternate text in this case

**Comment by tsingh777** [comment]
See suggestion in https://github.com/KhalisFoundation/sttm-desktop/pull/163

**Comment by maneetpaul** [comment]
The indicator is now present alongside the progress bar.
