### ISSUE TITLE
App Crashes on pressing space after selecting a SG Bani

### ISSUE THREAD

**Issue by MySmilingTurban** [KhalisFoundation/sttm-desktop#1641]
Steps to reproduce:

- Search any Shabad (or not)
- Open any Sundar Gutka Bani
- Press the space key, the App crashes

**Comment by theamanjs** [comment]
@MySmilingTurban veerji, can you give more input on this? I have tried this issue but I was unable to reproduce it.

**Comment by theamanjs** [comment]
Took help from @Gauravjeetsingh veerji on this. He was able to reproduce this issue on his machine. He's now working on fixing this.

**Comment by MySmilingTurban** [comment]
fixed in latest build
