### ISSUE TITLE
Bani Controller: changing SG Banis

### ISSUE THREAD

**Issue by MySmilingTurban** [KhalisFoundation/sttm-desktop#1642]
Steps to Reproduce:

- Connect with Bani Controller and choose and scroll through a Sundar Gutka Bani
- Try changing to some other bani, for example, asa di var, it doesn't work

**Comment by Gauravjeetsingh** [comment]
@MySmilingTurban I was unable to reproduce this, can you check again and see if there is a sequence by which you get this error?

**Comment by MySmilingTurban** [comment]
fixed in latest build
