### ISSUE TITLE
Hukamnama option not working, app crashes on multiple clicks on it (needs to be cross checked)

### ISSUE THREAD

**Issue by MySmilingTurban** [KhalisFoundation/sttm-desktop#1645]
Happened sometimes, but not always (kindly recheck)

Steps to reproduce:

- search some shabads
- Open Hukamnama, it doesn't open
- Click multiple times, app crashes

**Comment by MySmilingTurban** [comment]
In the latest build,
the hukamnama takes time to load
and the above mentioned issue persists.

**Comment by Gauravjeetsingh** [comment]
Looking into this.
