### ISSUE TITLE
Toggle logo isn't showing logo in Bani Overlay

### ISSUE THREAD

**Issue by MySmilingTurban** [KhalisFoundation/sttm-desktop#1652]
Steps to reproduce
- Open bani overlay and navigate through some banis
- Toggle logo in Bani Overlay menu, it doesn't show the logo

**Comment by Gauravjeetsingh** [comment]
@MySmilingTurban I tried 3-4 times, but was unable to reproduce this error. Can you check if there's a certain edge case when this happens?

**Comment by MySmilingTurban** [comment]
Sure Veerji, I'll retry and update you asap

**Comment by MySmilingTurban** [comment]
my apologies, it was the case with no background opacity in bani overlay
so technically, it was there but not visible as intended

**Comment by MySmilingTurban** [comment]
was visible again after raising background opacity
