### ISSUE TITLE
Auto-scroll acts weird on long shabads/banis using space

### ISSUE THREAD

**Issue by MySmilingTurban** [KhalisFoundation/sttm-desktop#1658]
Steps to reproduce:
1. search any long shabad say **p**anch **p**arvaan **p**anch **p**ardhan or anand sahib (bhog)
2. select first or last tuk as house tuk
3. click on the tuk at the other end
4. press space, notice how auto-scroll does the opposite of what's expected
it takes to the house panti when the highlight is on other pankti and vice versa

**Comment by Gauravjeetsingh** [comment]
Closing this out, as its released to prod.
