### ISSUE TITLE
Minimising Shortcut tray crashes app when in dark modes

### ISSUE THREAD

**Issue by MySmilingTurban** [KhalisFoundation/sttm-desktop#1659]
Steps to reproduce:
1. Choose any dark mode
2. Toggle the shortcut tray, the app crashes

Try the same thing in light modes, works fine

**Comment by saintsoldierx** [comment]
Verified issue exists on Mac

**Comment by Gauravjeetsingh** [comment]
Closing this out, as its released to prod.
