### ISSUE TITLE
Blank lines in Anand Karaj ceremony causes crash

### ISSUE THREAD

**Issue by saintsoldierx** [KhalisFoundation/sttm-desktop#1670]
(Auto generated from slack)
Blank lines in Anand Karaj ceremony causes crash
https://khalis.slack.com/archives/CFS6E54PN/p1665468381184469

**Comment by saintsoldierx** [comment]
<img width="661" alt="image" src="https://user-images.githubusercontent.com/27791330/195009427-027c2b12-bc37-430a-b9b4-977e08da451b.png">

**Comment by Gauravjeetsingh** [comment]
Fixed and merged in dev branch, alpha release
