### ISSUE TITLE
Lines in Anand Karaj are squashed together, should be middle and centered

### ISSUE THREAD

**Issue by saintsoldierx** [KhalisFoundation/sttm-desktop#1671]
(Auto generated from slack)
Lines in Anand Karaj are squashed together, should be middle and centered
https://khalis.slack.com/archives/CFS6E54PN/p1665468455691469

**Comment by saintsoldierx** [comment]
<img width="698" alt="image" src="https://user-images.githubusercontent.com/27791330/195009560-f224c70e-46ab-41b6-98e3-09d4728c25e2.png">

**Comment by Gauravjeetsingh** [comment]
This is fixed and merged in dev branch, alpha release
