### ISSUE TITLE
Next line is in wrong location on screen

### ISSUE THREAD

**Issue by saintsoldierx** [KhalisFoundation/sttm-desktop#1673]
(Auto generated from slack)
Next line is in wrong location on screen
https://khalis.slack.com/archives/CFS6E54PN/p1665469014124999

**Comment by saintsoldierx** [comment]
ONLY TESTED ON CHROMECAST
<img width="927" alt="image" src="https://user-images.githubusercontent.com/27791330/195010918-70c7cc1b-df2b-448f-811a-058b8fbaf9be.png">

**Comment by Gauravjeetsingh** [comment]
fixed and released to production. Closing this out
