### ISSUE TITLE
Akhand Paath View scroll and auto-scroll with line navigation not working (MacOS - v9.1.0 latest beta)

### ISSUE THREAD

**Issue by MySmilingTurban** [KhalisFoundation/sttm-desktop#1707]
Steps to reproduce:
- search any shabad and enable Akhand Paath View
- trying navigating through lines or scrolling (nothing works)

**Comment by Gauravjeetsingh** [comment]
Its working fine for me on windows, @theamanjs veerji, can you please check this on mac?
![apv](https://user-images.githubusercontent.com/1990932/211001953-ce866fd0-aff1-4599-9e7c-03002bf7c304.gif)

**Comment by MySmilingTurban** [comment]
Just rechecked, working fine on Mac as well.
There might be some weird combo on on my app at that time.
