### ISSUE TITLE
Windows build is giving a white screen without any UI?

### ISSUE THREAD

**Issue by Rewant90** [KhalisFoundation/sttm-desktop#1717]
May I know the Node version and other relevant details to make a proper windows built?
No error is coming while creating the build.

**Comment by theamanjs** [comment]
@Rewant90 this should work on node 16. If you still see a blank screen can you share errors that are showing on console?

**Comment by Rewant90** [comment]
Install
npm WARN deprecated set-value@0.2.0: Critical bug fixed in v3.0.1, please upgrade to the latest version.
npm WARN deprecated set-value@0.4.3: Critical bug fixed in v3.0.1, please upgrade to the latest version.
npm WARN deprecated set-value@0.3.3: Critical bug fixed in v3.0.1, please upgrade to the latest version.
npm WARN deprecated set-value@0.3.3: Critical bug fixed in v3.0.1, please upgrade to the latest version.
npm WARN deprecated set-value@0.3.3: Critical bug fixed in v3.0.1, please upgrade to the latest version.
npm WARN deprecated set-value@0.4.3: Critical bug fixed in v3.0.1, please upgrade to the latest version.
npm WARN deprecated set-value@0.4.3: Critical bug fixed in v3.0.1, please upgrade to the latest version.
npm WARN deprecated set-value@0.4.3: Critical bug fixed in v3.0.1, please upgrade to the latest version.
npm WARN deprecated set-value@0.3.3: Critical bug fixed in v3.0.1, please upgrade to the latest version.
npm WARN deprecated set-value@0.3.3: Critical bug fixed in v3.0.1, please upgrade to the latest version.
npm WARN deprecated set-value@0.3.3: Critical bug fixed in v3.0.1, please upgrade to the latest version.
npm WARN deprecated set-value@0.3.3: Critical bug fixed in v3.0.1, please upgrade to the latest version.
npm WARN deprecated set-value@0.4.3: Critical bug fixed in v3.0.1, please upgrade to the latest version.
npm WARN deprecated @npmcli/move-file@1.1.2: This functionality has been moved to @npmcli/fs
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated request-promise@4.2.6: request-promise has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
npm WARN deprecated i18next-node-fs-backend@2.1.3: replaced by i18next-fs-backend
npm WARN deprecated @npmcli/move-file@2.0.1: This functionality has been moved to @npmcli/fs
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated asar@3.2.0: Please use @electron/asar moving forward.  There is no API change, just a package name change
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated electron-osx-sign@0.6.0: Please use @electron/osx-sign moving forward. Be aware the API is slightly different
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated @babel/polyfill@7.12.1: 🚨 This package has been deprecated in favor of separate inclusion of a polyfill and regenerator-runtime (when needed). See the @babel/polyfill docs (https://babeljs.io/docs/en/babel-polyfill) for more information.
npm WARN deprecated noty@3.2.0-beta-deprecated: no longer supported
npm WARN deprecated electron-rebuild@3.2.9: Please use @electron/rebuild moving forward.  There is no API change, just a package name change
npm WARN deprecated core-js@2.6.12: core-js@<3.23.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Some versions have web compatibility issues. Please, upgrade your dependencies to the actual version of core-js.

build 
> sttm-desktop@9.1.0 pack:win
> npm run build && electron-builder --win --x64


> sttm-desktop@9.1.0 build
> npm run build-css & npm run build-js


> sttm-desktop@9.1.0 build-css
> run-p build-css:*


> sttm-desktop@9.1.0 build-js
> rm -rf www/js & babel ./www/main -d ./www/js


> sttm-desktop@9.1.0 build-css:main
> node-sass --output-style compressed --include-path www/src/scss www/src/scss/styles.scss www/assets/css/bundle.css


> sttm-desktop@9.1.0 build-css:obs
> node-sass --output-style compressed --include-path www/src/scss/obs www/src/scss/obs/styles.scss www/obs/bundle.css

Rendering Complete, saving .css file...
Wrote CSS to /Users/vikrantupadhyay/Desktop/sikhi_to_max_desktopApp/www/obs/bundle.css
Rendering Complete, saving .css file...
Wrote CSS to /Users/vikrantupadhyay/Desktop/sikhi_to_max_desktopApp/www/assets/css/bundle.css
Successfully compiled 204 files with Babel (1545ms).
  • electron-builder  version=23.6.0 os=21.6.0
  • loaded configuration  file=package.json ("build" field)
  • electron-rebuild not required if you use electron-builder, please consider to remove excess dependency from devDependencies

To ensure your native dependencies are always matched electron version, simply add script `"postinstall": "electron-builder install-app-deps" to your `package.json`
  • writing effective config  file=builds/builder-effective-config.yaml
  • rebuilding native dependencies  dependencies=mdns@2.7.2 platform=win32 arch=x64
  • packaging       platform=win32 arch=x64 electron=19.1.9 appOutDir=builds/win-unpacked
  • downloading     url=https://github.com/electron/electron/releases/download/v19.1.9/electron-v19.1.9-win32-x64.zip size=88 MB parts=8
  • downloaded      url=https://github.com/electron/electron/releases/download/v19.1.9/electron-v19.1.9-win32-x64.zip duration=19.388s
  • building        target=nsis file=builds/SikhiToTheMaxSetup-9.1.0.exe archs=x64 oneClick=true perMachine=true
  • building block map  blockMapFile=builds/SikhiToTheMaxSetup-9.1.0.exe.blockmap

**Comment by Rewant90** [comment]
Still giving blank screen, it's not giving any error. I'm able to create proper Mac Built

**Comment by Rewant90** [comment]
@theamanjs Please help

**Comment by theamanjs** [comment]
@Rewant90 are you able to run this project on dev environment?

**Comment by Rewant90** [comment]
Yes. I am able to run the application, everything is working fine there

**Comment by Rewant90** [comment]
@theamanjs

**Comment by theamanjs** [comment]
@Rewant90 when you run the application you will be able to open the console (dev tool) by pressing `ctrl + shift + i`. Can you share the screenshot of that output?

PS I hope you are using `npm run pack:win` while making the build

**Comment by Rewant90** [comment]
[https://drive.google.com/file/d/1P0ANQHAJ8K7Nw92I8K3TUkBHh6U9T_QF/view?usp=sharing](url)

yes, I am able to run and open the console, i'm also using npm run pack:win for the built @theamanjs

**Comment by theamanjs** [comment]
@Rewant90 I'm sorry for the confusion. I meant when you will open the build that is causing you the issue. You can open the dev tool of the application by pressing `ctrl + shift + i` while you are seeing that white blank screen.

It may sound basic but information like operating system and CPU architecture would help. If you are using the operating system in a VM machine please let me know that as well.

I hope you are doing this for some testing or development purposes. Nevertheless, if you just want to use a public version of the application you can download the latest version using this link http://releases.khalis.net/sttm/win-x64/latest

**Comment by Rewant90** [comment]
I am using it for some testing and development purpose. I am using it in my windows laptop after building it in my Macbook. 
I am sending you that

**Comment by Rewant90** [comment]
I read in one of the issues that in windows build is not happening, its having issues. Its giving a lot of errors, can you share the configs for windows build?

**Comment by Rewant90** [comment]
https://drive.google.com/file/d/1_sbQkN7ZUXemQeV6KzNj7vhpmHZuxVQ-/view?usp=sharing

Please help.

**Comment by Rewant90** [comment]
@theamanjs

**Comment by theamanjs** [comment]
> I read in one of the issues that in windows build is not happening, its having issues. Its giving a lot of errors, can you share the configs for windows build?

Can you share that issue here? 

We have updated the code in last public release and it must be working now. You can try creating build on windows machine. Let me know if that still creates issue there.

**Comment by Rewant90** [comment]
Microsoft Windows [Version 10.0.22621.1105]
(c) Microsoft Corporation. All rights reserved.

C:\Users\rewan\sttm-desktop>npm i
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
npm WARN deprecated set-value@0.4.3: Critical bug fixed in v3.0.1, please upgrade to the latest version.
npm WARN deprecated set-value@0.3.3: Critical bug fixed in v3.0.1, please upgrade to the latest version.
npm WARN deprecated set-value@0.3.3: Critical bug fixed in v3.0.1, please upgrade to the latest version.
npm WARN deprecated set-value@0.3.3: Critical bug fixed in v3.0.1, please upgrade to the latest version.
npm WARN deprecated set-value@0.4.3: Critical bug fixed in v3.0.1, please upgrade to the latest version.
npm WARN deprecated set-value@0.4.3: Critical bug fixed in v3.0.1, please upgrade to the latest version.
npm WARN deprecated set-value@0.4.3: Critical bug fixed in v3.0.1, please upgrade to the latest version.
npm WARN deprecated set-value@0.3.3: Critical bug fixed in v3.0.1, please upgrade to the latest version.
npm WARN deprecated set-value@0.3.3: Critical bug fixed in v3.0.1, please upgrade to the latest version.
npm WARN deprecated set-value@0.3.3: Critical bug fixed in v3.0.1, please upgrade to the latest version.
npm WARN deprecated set-value@0.2.0: Critical bug fixed in v3.0.1, please upgrade to the latest version.
npm WARN deprecated set-value@0.4.3: Critical bug fixed in v3.0.1, please upgrade to the latest version.
npm WARN deprecated set-value@0.3.3: Critical bug fixed in v3.0.1, please upgrade to the latest version.
npm WARN deprecated request-promise@4.2.6: request-promise has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated i18next-node-fs-backend@2.1.3: replaced by i18next-fs-backend
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated @babel/polyfill@7.12.1: 🚨 This package has been deprecated in favor of separate inclusion of a polyfill and regenerator-runtime (when needed). See the @babel/polyfill docs (https://babeljs.io/docs/en/babel-polyfill) for more information.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated noty@3.2.0-beta-deprecated: no longer supported
npm WARN deprecated core-js@2.6.12: core-js@<3.23.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Some versions have web compatibility issues. Please, upgrade your dependencies to the actual version of core-js.
npm ERR! code 1
npm ERR! path C:\Users\rewan\sttm-desktop\node_modules\mdns
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node-gyp rebuild
npm ERR! Building the projects in this solution one at a time. To enable parallel build, please add the "-m" switch.
npm ERR!   dns_sd.cpp
npm ERR! C:\Users\rewan\sttm-desktop\node_modules\mdns\src\mdns.hpp(32,10): fatal  error C1083: Cannot open include file: 'dns_sd.h': No such file or directory [C:\Users\rewan\sttm-desktop\node_modules\mdns\build\dns_sd_bindings.vcxproj]
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@9.1.0
npm ERR! gyp info using node@16.16.0 | win32 | x64
npm ERR! gyp info find Python using Python version 3.11.0 found at "C:\Python311\python.exe"
npm ERR! gyp info find VS using VS2022 (17.4.33213.308) found at:
npm ERR! gyp info find VS "C:\Program Files\Microsoft Visual Studio\2022\Enterprise"
npm ERR! gyp info find VS run with --verbose for detailed information
npm ERR! gyp info spawn C:\Python311\python.exe
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   'C:\\Users\\rewan\\sttm-desktop\\node_modules\\node-gyp\\gyp\\gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'msvs',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   'C:\\Users\\rewan\\sttm-desktop\\node_modules\\mdns\\build\\config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   'C:\\Users\\rewan\\sttm-desktop\\node_modules\\node-gyp\\addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   'C:\\Users\\rewan\\AppData\\Local\\node-gyp\\Cache\\16.16.0\\include\\node\\common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=C:\\Users\\rewan\\AppData\\Local\\node-gyp\\Cache\\16.16.0',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\rewan\\sttm-desktop\\node_modules\\node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=C:\\\\Users\\\\rewan\\\\AppData\\\\Local\\\\node-gyp\\\\Cache\\\\16.16.0\\\\<(target_arch)\\\\node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=C:\\Users\\rewan\\sttm-desktop\\node_modules\\mdns',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'C:\\Users\\rewan\\sttm-desktop\\node_modules\\mdns\\build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp info spawn C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\MSBuild.exe
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   'build/binding.sln',
npm ERR! gyp info spawn args   '/clp:Verbosity=minimal',
npm ERR! gyp info spawn args   '/nologo',
npm ERR! gyp info spawn args   '/p:Configuration=Release;Platform=x64'
npm ERR! gyp info spawn args ]
npm ERR! gyp ERR! build error
npm ERR! gyp ERR! stack Error: `C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\MSBuild.exe` failed with exit code: 1      
npm ERR! gyp ERR! stack     at ChildProcess.onExit (C:\Users\rewan\sttm-desktop\node_modules\node-gyp\lib\build.js:201:23)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:527:28)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:291:12)
npm ERR! gyp ERR! System Windows_NT 10.0.22621
npm ERR! gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\rewan\\sttm-desktop\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"    
npm ERR! gyp ERR! cwd C:\Users\rewan\sttm-desktop\node_modules\mdns
npm ERR! gyp ERR! node -v v16.16.0
npm ERR! gyp ERR! node-gyp -v v9.1.0
npm ERR! gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\rewan\AppData\Local\npm-cache\_logs\2023-01-31T07_58_13_401Z-debug-0.log


@theamanjs This is what I am getting while installing

**Comment by Rewant90** [comment]
@theamanjs Any insights?

**Comment by theamanjs** [comment]
Hey @Rewant90, @Gauravjeetsingh will take over on this issue.

**Comment by Rewant90** [comment]
@Gauravjeetsingh Can you please assist?

**Comment by Rewant90** [comment]
@Gauravjeetsingh Any update?

**Comment by Gauravjeetsingh** [comment]
Hi @Rewant90, the logs you shared above are from a windows machine, or a virtual machine inside mac?

Also, can you please share the node and npm version.

**Comment by Rewant90** [comment]
Yes, those logs are from a windows, when I'm building it from Mac it's giving a blank screen.. when I'm trying from windows it's showing these errors. I have tried node v- 16.16.0 on both windows and MacBook.

**Comment by Rewant90** [comment]
@Gauravjeetsingh

**Comment by Rewant90** [comment]
NVM Version
 - 8.11.0

**Comment by Rewant90** [comment]
Can you give me the mac book or  windows branch name and config from which build is happening?

**Comment by hardevs** [comment]
@Rewant90 Also try disabling Anti-Virus and any other security apps like Firewall, DNS Filtering, etc.

**Comment by Rewant90** [comment]
I have tried all that ,also I have tried making the build from 3 devices and also on maconcloud.

**Comment by Rewant90** [comment]
@hardevs

**Comment by Rewant90** [comment]
Hi, Any updates on this issue?

**Comment by saintsoldierx** [comment]
@Gauravjeetsingh can you assist?

**Comment by Gauravjeetsingh** [comment]
Hi @Rewant90, looks like you need to install the Bonjour print services, 
https://support.apple.com/kb/DL999?locale=en_US

Can you please install this on your windows machine, and see if this solves it.

**Comment by Rewant90** [comment]
The issue is still there.
I have a few questions,
Are you making the built just via Mac book?
What are the configs?
Node version, python version etc,
If you are able to make a built via windows, what are the additional requirements?
Which all branches are having a stable built?
@Gauravjeetsingh 
Thanks in Advance

**Comment by Rewant90** [comment]
Just to remind, I am not able to create the built on Windows, it throwing a lot of errors.
When i am creating the built on Macbook, it is making the DMG perfectly but the After i install the Exe on windows I am having a completely blank screen.
@Gauravjeetsingh

**Comment by Rewant90** [comment]
Any update ? @Gauravjeetsingh @saintsoldierx

**Comment by Gauravjeetsingh** [comment]
Hi @Rewant90 ji, if you can give me access to the code you are trying to compile, i can test it on my machine and see if I am able to get it working.

**Comment by Gauravjeetsingh** [comment]
Had a call about this today with Rewant ji and his team.

Problem statement, which I understood:
They didn't change the code much, they only changed few assets like logo and images. And also, added a different source for translations. But they couldn't create a build on windows. But mac build is working fine.

Things I suggested them to make it work:
- Link their own appveyor account, and use the appveyor script given in the repo to create a build.
- Remove the package-lock.json, and the node_modules folder, and then run npm install and create build after that.
- Try using a different windows machine, with a fresh install of nodejs, and npm and setup the app there.

Also, @Rewant90 ji, are you using a github repo with your changes, it would be helpful if you can share the repo link here.

p.s. I did get the dump of code via a zip file in email, will look through it and debug.

**Comment by pdvsingh** [comment]
@Rewant90 changing the translation source would be against the license terms of BaniDB. Can you please explain what your intent is to change the translations, perhaps we can find a different solution to help you out.

**Comment by Gauravjeetsingh** [comment]
Closing this out.
