### ISSUE TITLE
English searching should show results in english?

### ISSUE THREAD

**Issue by saintsoldierx** [KhalisFoundation/sttm-desktop#1723]
<img width="684" alt="image" src="https://user-images.githubusercontent.com/27791330/217482753-5e85566e-ac61-497c-897b-d646319f5298.png">
I feel the english searching should show the results transliterated rather than in Gurmukhi OR with transliteration on one row and Gurmukhi below it? (or vice versa).

**Comment by theamanjs** [comment]
We can add the transliteration below the Gurmukhi verse same as being done in sikhitothemax.org here
https://www.sikhitothemax.org/search?q=dde&type=7&source=all&writer=all

**Comment by Gauravjeetsingh** [comment]
This has been pushed to production, closing this out.
