### ISSUE TITLE
Use bonjour for local desktop to desktop discovery

### ISSUE THREAD

**Issue by ManjotS** [KhalisFoundation/sttm-desktop#173]
Depends on #172 

https://www.npmjs.com/package/bonjour

Desktop can publish its code and socket to local network and allow discovery without internet.

**Comment by prebhdevsingh** [comment]
this would require the gurdwara or the kirtan host to share their local wifi password with others. Do we really need it?

would rather promote the QR code feature with some sort of pin to allow connecting to the session. Going to close this one unless you differ with my assessment.
