### ISSUE TITLE
Intelligent spacebar causing issues Win 11

### ISSUE THREAD

**Issue by ManjotS** [KhalisFoundation/sttm-desktop#1753]
<div> Freshdesk Ticket ID: <a href="https://khalis.freshdesk.com/a/tickets/7237">7237</a></div>
                       <div> Freshdesk Ticket Agent: Aman Singh</div>
                       <div> Freshdesk Ticket Agent Email: saintsoldierx@gmail.com</div>
                       <div> Ticket Priority: Low</div>
                       <div> Freshdesk Ticket Description: </div><div>The intelligent spacebar functionality doesn't seem to work in the April 25 release on Windows 11. Daas di benti parvaan karo ji and please revert this change. It was working just fine before. It is now unpredictable and it doesn't return to the home pangti as expected. It is confusing for the sangat with the viewer jumping to the wrong pangtia.

</div>

**Comment by ManjotS** [comment]
<div>Agent Aman Singh linked Freshdesk ticket <a href="https://khalis.freshdesk.com/a/tickets/7237">7237</a> for this issue.</div>

**Comment by Gauravjeetsingh** [comment]
Closing this issue, since we have another issue to toggle between intelligent spacebar.
https://github.com/KhalisFoundation/sttm-desktop/issues/1761
