### ISSUE TITLE
Save shabad change with arrow right/left in history

### ISSUE THREAD

**Issue by inderpreetsingh** [KhalisFoundation/sttm-desktop#1759]
> @theamanjs veerji, do you know if we want to save the shabads opened with left and right buttons in the history?
> 
> This PR fixes the tick on reading verse, but it still won't add the opened shabads in the history,

I think this was never a part of the functionality. However, we can do that in a separate PR.

_Originally posted by @theamanjs in https://github.com/KhalisFoundation/sttm-desktop/issues/1747#issuecomment-1543857261_

**Comment by Gauravjeetsingh** [comment]
This has been pushed to production, closing this out.
