### ISSUE TITLE
Two scroll bars and small search result issue

### ISSUE THREAD

**Issue by theamanjs** [KhalisFoundation/sttm-desktop#1765]
@theamanjs veerji
There are two scrollbars in shabad pane in single display mode. Can you fix it the same way.
![Screenshot from 2023-06-02 11-08-48](https://github.com/KhalisFoundation/sttm-desktop/assets/1990932/bfac40aa-de9f-4f28-b0d8-0c9e93c2f9e7)

Also, the current height of search results seemed a little less on my laptop screen (1366 x 768), I can only see two shabads without scrolling. What if we set a min-height to this complete pane, which would give more space to the search results, automatically. 

![Screenshot from 2023-06-02 11-09-00](https://github.com/KhalisFoundation/sttm-desktop/assets/1990932/f2d030d4-b085-45b5-96ae-ce929f8f450e)

_Originally posted by @Gauravjeetsingh in https://github.com/KhalisFoundation/sttm-desktop/issues/1760#issuecomment-1573183879_

**Comment by Gauravjeetsingh** [comment]
Fixed and released
