### ISSUE TITLE
Web User Report

### ISSUE THREAD

**Issue by bogas04** [KhalisFoundation/sttm-desktop#177]
Please select which platform you are using:-
Web Version

Feedback Type
Enhancements

What went wrong?
Presentation mode similar to PowerPoint in desktop version

What should have happened instead?

How can the issue be recreated by our team?
Line by line or split view

Which web browser are using?

Operating System

Name
Jagjinder Singh

**Comment by bogas04** [comment]
Hmm, maybe it's web issue. They want presentation mode in web? @ManjotS

**Comment by ManjotS** [comment]
@saintsoldierx can we email back and suggest they download desktop?
