### ISSUE TITLE
9.1.2 (MacOS) - Quick tools - Unable to click transliteration view toggle due to overlap with logo

### ISSUE THREAD

**Issue by MySmilingTurban** [KhalisFoundation/sttm-desktop#1775]
Steps to reproduce
- open quick tools
- try to toggle transliteration view button

It is clickable just at the top of icon, but should be clickable throughout the icon
maybe caused due to the overlap with logo

<img width="802" alt="Screenshot 2023-06-21 at 8 54 20 am" src="https://github.com/KhalisFoundation/sttm-desktop/assets/51584037/2d38608f-abb7-4d8b-8909-063c4594e203">

**Comment by Gauravjeetsingh** [comment]
It's working fine for me on windows and macbook, @theamanjs veerji can you please check

**Comment by MySmilingTurban** [comment]
I forgot to mention, it happens only when you are in Akhand Paath View.

**Comment by Gauravjeetsingh** [comment]
Fix released in production, closing this out.
