### ISSUE TITLE
9.1.3 (MacOS) - Dhan Guru slides and Akhand Paath View combo error

### ISSUE THREAD

**Issue by MySmilingTurban** [KhalisFoundation/sttm-desktop#1776]
Steps to reproduce:
- Go to any shabad and navigate using Akhand Paath View
- Show a guru slide, notice it shows repeated name of Guru sahib
- Also, when you go back to shabad, it gets stuck (navigation doesn't work)

**Comment by theamanjs** [comment]
Moving this issue to 9.1.3 Since we gotta release 9.1.2 and it's the priority

**Comment by Gauravjeetsingh** [comment]
This has been pushed to production, closing this out.
