### ISSUE TITLE
Downloaded application says "Sikhi To The Max 3"

### ISSUE THREAD

**Issue by prebhdevsingh** [KhalisFoundation/sttm-desktop#178]
![image](https://user-images.githubusercontent.com/9758101/41503654-d3b91fec-718d-11e8-9407-b944a5a6eab3.png)

Prompt that "application downloaded from the internet" also says "Sikhi To The Max 3".

**Comment by tarunsingh5** [comment]
I think it only says this if you have 3 instances of the application installed - we should confirm first

**Comment by inderpreetsingh** [comment]
Yup! Couldn't reproduce on my end! - it shows sikhiToTheMax for me.

**Comment by tarunsingh5** [comment]
closing this out since we were not able to replicate
