### ISSUE TITLE
Switching to Akhand Path Sahib view clears the presenter

### ISSUE THREAD

**Issue by prebhdevsingh** [KhalisFoundation/sttm-desktop#179]
Steps to re-produce -

1. Open a shabad with Akhand Path Sahib turned off
2. Turn on akhand path sahib view
3. You lose the shabad which was displaying in the presenter view

**Comment by prebhdevsingh** [comment]
Please test w/o presenter view

**Comment by tarunsingh5** [comment]
this was done intentionally due to the way APV was implemented.

@navdeepsinghkhalsa can comment more
