### ISSUE TITLE
9.1.2 (MacOS) - Filter results are not visible

### ISSUE THREAD

**Issue by MySmilingTurban** [KhalisFoundation/sttm-desktop#1796]
Steps to reproduce

1. Search 'jmh' and add filter for writer guru amar das sahib ji, or try any other filters
2. The number of results shows 9 results but none are visible and openable

<img width="694" alt="Screenshot 2023-07-05 at 11 14 01 pm" src="https://github.com/KhalisFoundation/sttm-desktop/assets/51584037/33703e02-b1de-4240-a6eb-57139240186f">

**Comment by Gauravjeetsingh** [comment]
Fix released in production, closing this out.
