### ISSUE TITLE
9.1.2 (MacOS) - Custom image not visible

### ISSUE THREAD

**Issue by MySmilingTurban** [KhalisFoundation/sttm-desktop#1798]
Steps to reproduce

1. choose custom image option from Quick insert
2. select any image, it doesn't show up on screen

**Comment by theamanjs** [comment]
@MySmilingTurban veerji, I'm unable to reproduce this issue. Can you please check this?

https://github.com/KhalisFoundation/sttm-desktop/assets/38748298/9ddebbe0-712b-4395-8669-449bf704c5fb
