### ISSUE TITLE
Present next line in a different style

### ISSUE THREAD

**Issue by prebhdevsingh** [KhalisFoundation/sttm-desktop#182]
We should show the next line in a lighter color so it's clear this is the next panktee.

**Comment by ManjotS** [comment]
And 90% font size

**Comment by navdeepsinghkhalsa** [comment]
This will need to be done in `src/scss/_display-next-line.scss`
Change the font-size value to calculate $i * 0.9 on line 3
Developer will also have to work with @saintsoldierx to define a colour for next line for each theme and write the rules in the respective SCSS theme files

**Comment by lbk003** [comment]
@saintsoldierx Can you please specify the color for next line for each theme.

**Comment by saintsoldierx** [comment]
Rather than color, should we do opacity=50% for next line?

**Comment by lbk003** [comment]
Fixed with https://github.com/KhalisFoundation/sttm-desktop/pull/215
