### ISSUE TITLE
9.1.3 (Win10 & MacOS) - Guru icon has different color

### ISSUE THREAD

**Issue by MySmilingTurban** [KhalisFoundation/sttm-desktop#1822]
Steps to reproduce:
- Open app, and look at the bottom-right corner panel
- Notice icon for Guru has darker color than other icons

![Screenshot 2023-09-02 at 10 58 03 am](https://github.com/KhalisFoundation/sttm-desktop/assets/51584037/15922527-24d0-42a9-a898-7706a5742b9c)
![Screenshot 2023-09-02 at 10 56 42 am](https://github.com/KhalisFoundation/sttm-desktop/assets/51584037/4616291b-ee25-4726-b6f2-64b7f332efc3)

**Comment by Gauravjeetsingh** [comment]
This has been pushed to production, closing this out.
