### ISSUE TITLE
9.1.3 (Win10) - App shows code in file menu

### ISSUE THREAD

**Issue by MySmilingTurban** [KhalisFoundation/sttm-desktop#1823]
Steps to reproduce:
- Open app in windows 10 device
- Open File menu 
- Notice it shows "Quit {{appName}}" instead of "Quit SikhiToTheMax"

![winissue](https://github.com/KhalisFoundation/sttm-desktop/assets/51584037/c0ab5c94-05d2-45e8-b130-b99663ee9518)

**Comment by Gauravjeetsingh** [comment]
This has been pushed to production, closing this out.
