### ISSUE TITLE
9.1.3 (Win10 + MacOS) - Announcements typing issue

### ISSUE THREAD

**Issue by MySmilingTurban** [KhalisFoundation/sttm-desktop#1824]
Typing spacebar in announcement changes the slide, also navigating within text using arrow keys also changes slides

Steps to reproduce:
- Open any shabad
- Try to add a new announcements (with spaces in it)
- Notice while writing, everytime you type spacebar it changes the slide

**Comment by Gauravjeetsingh** [comment]
This has been pushed to production, closing this out.
