### ISSUE TITLE
9.1.3 (Win10 + MacOS) - Gurmukhi toggle issue in announcements and guru slides

### ISSUE THREAD

**Issue by MySmilingTurban** [KhalisFoundation/sttm-desktop#1825]
Switching the Gurmukhi toggle in Announcement tab changes Gurmukhi in Dhan guru tab too but the switch remains disabled.

Steps to reproduce:
- Ensure announcement gurmukhi toggle is off
- Add a dhan guru slide and enable gurmukhi
- Open announcements tab, notice it is taking input for gurmukhi but the switch(button) is disabled

![gurmukhitoggle](https://github.com/KhalisFoundation/sttm-desktop/assets/51584037/f66ab96e-536f-45fe-b6d5-7ae1465a26cb)

**Comment by Gauravjeetsingh** [comment]
This has been pushed to production, closing this out.
