### ISSUE TITLE
Changes in Favorite shabad UI

### ISSUE THREAD

**Issue by Gauravjeetsingh** [KhalisFoundation/sttm-desktop#1839]
- Change the color of date-time to light grey
- Decrease the size of red delete icon 
- Remove clock icon
- Remove Add to fav from header, use a star icon to favorite the shabad
- Favorites instead of Favorite in pane name

**Comment by Gauravjeetsingh** [comment]
@saintsoldierx / @inderpreetsingh veerji, this is the newer UI, I have so far for favorite shabad, any other change required in this?

Favorite shabad pane
![image](https://github.com/KhalisFoundation/sttm-desktop/assets/1990932/92302240-7599-4786-a60b-bd1a3e399690)

On hover (if the mouse pointer is over the delete icon, it turns red, else it stays same)
![image](https://github.com/KhalisFoundation/sttm-desktop/assets/1990932/6e865edf-c55c-4302-a099-cf51c3a3dd42)

Favorite button is now just a star icon
![image](https://github.com/KhalisFoundation/sttm-desktop/assets/1990932/99609925-fce8-4dcf-ac7d-c6238205dec7)
![image](https://github.com/KhalisFoundation/sttm-desktop/assets/1990932/c1f987c8-5999-41fa-a65c-98ca7dd9e4d1)

**Comment by saintsoldierx** [comment]
I like it - I think some may object to the trash icon though with it being Gurbani. Change to some other?
