### ISSUE TITLE
where are live feed text files when I turn it on? what is it? help has no info.

### ISSUE THREAD

**Issue by ManjotS** [KhalisFoundation/sttm-desktop#184]
Manjot Singh [8 minutes ago]
hover tooltips are good

Manjot Singh [8 minutes ago]
we should also add it to the help (help menu, and on site)

**Comment by maneetpaul** [comment]
Discussion that was had in Slack regarding how this should look. It was decided to add a toggle in the controller with the directory path underneath it. 

We need a way for the user to see whats the current set directory and change it.

@inderpreetsingh is this something you can implement? or is further input needed regarding UI/UX?

**Comment by tarunsingh5** [comment]
#152

**Comment by tsingh777** [comment]
https://github.com/KhalisFoundation/sttm-desktop/pull/328
