### ISSUE TITLE
Add SHARE Trademark info in About us popup

### ISSUE THREAD

**Issue by prebhdevsingh** [KhalisFoundation/sttm-desktop#189]
Trademark SHARE Charity, UK

![image](https://user-images.githubusercontent.com/9758101/41696578-9efde7ee-74c9-11e8-8ec3-5f8c890d2aac.png)

**Comment by ManjotS** [comment]
this should go further and include @saintsoldierx suggestions.

![image](https://user-images.githubusercontent.com/644885/41699678-d3ee6982-74d9-11e8-97d4-c9ba3787b780.png)

Copyright text should match web.

Then lets add:
Special thanks to volunteer developers from around the globe, including:
Navdeep Singh Khalsa, Inderpreet Singh, Divjot Singh, Taranjit Singh, Ishmeet Singh, Harkeerat Singh, Harpreet Singh, Irvanjit Singh, Manraj Singh, Tarsem Singh

**Comment by ManjotS** [comment]
Also lets add the link to privacy policy and TOS on website.

**Comment by tarunsingh5** [comment]
@inderpreetsingh can you do this asap?

**Comment by tarunsingh5** [comment]
@prebhdevsingh any progress here? if not - @ManjotS can you take this on? lets close these simple tickets out

**Comment by tsingh777** [comment]
^ Balwinder Kaur.

**Comment by tsingh777** [comment]
There seems to be a limit on how long the copy right can be. At the moment this window is generated by [electron-builder](https://www.npmjs.com/package/electron-builder) and not much options seem to be available (https://www.electron.build/configuration/configuration#configuration). opened https://github.com/KhalisFoundation/sttm-desktop/pull/275 that adds the extended copyright. 

need to investigate further on adding the special thanks and other links. https://www.npmjs.com/package/about-window seems promising if others want to take a look.

**Comment by tarunsingh5** [comment]
this is probably good enough for now

**Comment by tsingh777** [comment]
We can either repurpose this to add the special thanks or open a new issue for that.

**Comment by tarunsingh5** [comment]
closing issue since share is now mentioned in 4.1

**Comment by ManjotS** [comment]
I want to leave  it open for a future redesign.  Ive been playing with  it.

**Comment by maneetpaul** [comment]
In order to avoid confusion with work that was already done, I am going to close this. @ManjotS feel free to open a new issue to track any future changes.
