### ISSUE TITLE
Create a new multi-pane workspace

### ISSUE THREAD

**Issue by saintsoldierx** [KhalisFoundation/sttm-desktop#1912]
![STTM-BaniOverlay copy](https://github.com/KhalisFoundation/sttm-desktop/assets/27791330/55b9880f-dcd2-4657-9f74-8f2de344b5b1)
![STTM-MultiPane copy](https://github.com/KhalisFoundation/sttm-desktop/assets/27791330/0ca16a9b-c7ef-4b92-b0f0-55fe995cee9a)

1. I can select a multi-pane workspace when I need three or more Shabad panes.
2. I can select lines from three different Shabads or compiled Baanis.
3. I can search for a Shabad and select which pane (1-3) to display the Shabad in for line selection.
4. I can set a default pane (1-3) for Shabad selection. When I click on a Shabad line and don’t select a pane (1-3) from the search result list, it will send the Shabad to the pane that has been selected as default.
5. I can lock a pane so I accidentally do not select it when selecting a Shabad. 
6. I can search history of Shabads. This should not be pane-specific but has all the history from all the panes. 
7. The history will show in that pane until I select a Shabad or click the history icon again. 
8. The history icon will highlight to show it has been selected.
9. I can clear a pane of the Shabad when I click the clear icon.
10. Under Sundar Gutka, Ceremonies and Announcements, there will be three 1-3 buttons which I can select one at a time that will default to which pane the Baani/Dhan Guru I select goes to.
11. I can click the + icon to add options from Quick Insert and Others menu (random shabad/hukamnama)
12. I can click heart icon for favorites and select from my previously favorited shabads.

**Comment by Gauravjeetsingh** [comment]
- I can select a multi-pane workspace when I need three or more Shabad panes.
Is 3 not a fixed number of panes, we can have more than 3 as well?

- I can lock a pane so I accidentally do not select it when selecting a Shabad.
Should we set by default the currently active pane as locked? As in, the currently active shabad pane would always locked, but can be unlocked if we want to.

**Comment by saintsoldierx** [comment]
1. No, sorry it should only be three panes for now. We can add option for 2 panes later.
2. We could do it that current active pane is locked, that is a good idea I think.

**Comment by Gauravjeetsingh** [comment]
Fixed and released to production.
