### ISSUE TITLE
New Theme

### ISSUE THREAD

**Issue by SukhmanpreetSingh** [KhalisFoundation/sttm-desktop#193]
Using this graphic we can create a new theme

![up design](https://user-images.githubusercontent.com/33250386/42408291-f08791e8-81e7-11e8-83e7-89e1191fa5ba.JPG)

**Comment by saintsoldierx** [comment]
Not hi-res enough...

**Comment by ManjotS** [comment]
Can we get a vector made on Fiverr @saintsoldierx
