### ISSUE TITLE
9.2.1 (Win+MacOS) - Hovering on locked pane in search results shows clickable cursor on lock

### ISSUE THREAD

**Issue by MySmilingTurban** [KhalisFoundation/sttm-desktop#1930]
Hovering on locked pane number in search results shows clickable cursor on lock

https://github.com/KhalisFoundation/sttm-desktop/assets/51584037/160cf910-609e-454d-b846-fd8b8ee8e21c

Steps to reproduce
1. Lock a shabad pane in multipane view
2. Search any shabad and hover over the locked pane in search results, notice it shows clickable cursor even though it is disabled

**Comment by Gauravjeetsingh** [comment]
Fixed and released to production.
