### ISSUE TITLE
9.2.1 (Win+MacOS) - Unable to navigate through any shabad using arrow keys or spacebar

### ISSUE THREAD

**Issue by MySmilingTurban** [KhalisFoundation/sttm-desktop#1931]
Unable to navigate through any shabad using arrow keys or spacebar
**App crashes when you open Presentation view after trying to navigate with spacebar**

Steps to reproduce
1. Search any shabad and open it in multipane view
2. Try using arrow keys or spacebar to navigate through the shabad, notice it doesn't work

**Comment by Gauravjeetsingh** [comment]
Fixed and released to production.
