### ISSUE TITLE
9.2.1 (Win+MacOS) - Search results go blank when scrolling to bottom in ang search

### ISSUE THREAD

**Issue by MySmilingTurban** [KhalisFoundation/sttm-desktop#1932]
Search results go blank when scrolling to bottom in ang search

https://github.com/KhalisFoundation/sttm-desktop/assets/51584037/c8036a09-62b7-4ab7-97e7-a0e384cbdeae

Steps to reproduce
1. Search 917 and scroll down in the search results
2. Once you reach the bottom, notice that search results disappear

**Comment by Gauravjeetsingh** [comment]
Fixed and released to production.
