### ISSUE TITLE
9.2.1 (Win+MacOS) - Scrollbar overlaps multipane header's coloured border (Minor UI issue)

### ISSUE THREAD

**Issue by MySmilingTurban** [KhalisFoundation/sttm-desktop#1933]
Minor UI issue - Scrollbar overlaps multipane header's coloured border
<img width="557" alt="Screenshot 2024-05-12 at 7 37 16 PM" src="https://github.com/KhalisFoundation/sttm-desktop/assets/51584037/ff0a51c1-9266-439a-a651-2924a4e6dfc9">

Steps to reproduce
1.  Choose a light theme and open "kjrGlr" shabad in multipane view
2. Scroll so the scrollbar touches the top, notice it overlaps header's bottom border

**Comment by Gauravjeetsingh** [comment]
Fixed and released to production.
