### ISSUE TITLE
9.2.1 (Win+MacOS) - Multipane header bottom border disappears in dark themes

### ISSUE THREAD

**Issue by MySmilingTurban** [KhalisFoundation/sttm-desktop#1934]
Multipane header bottom border disappears in dark themes

https://github.com/KhalisFoundation/sttm-desktop/assets/51584037/1bdf2f6c-1cc0-40c1-a7d8-8475decf8145

Steps to reproduce
1. Open multipane view and choose a dark theme, notice the coloured border on the bottom of header of shabad panes disappears

**Comment by Gauravjeetsingh** [comment]
@MySmilingTurban veerji, I can see the border in dark themes too, which dark theme exactly did you select for this?

<img width="779" alt="image" src="https://github.com/KhalisFoundation/sttm-desktop/assets/1990932/1eb4a974-7120-4486-aa90-6a27d226b0aa">

**Comment by MySmilingTurban** [comment]
@Gauravjeetsingh veerji, its not visible on any dark themes on my end
<img width="1666" alt="image" src="https://github.com/KhalisFoundation/sttm-desktop/assets/51584037/78c03191-bb37-4255-beb7-258d9dbea996">

**Comment by Gauravjeetsingh** [comment]
@MySmilingTurban veerji, is this from mac or windows?

**Comment by Gauravjeetsingh** [comment]
This wasn't reproduced in recent builds, and is now pushed to production, if it comes again, we can reopen this, closing this out for now.
