### ISSUE TITLE
9.2.1 (Win+MacOS) - Sync/BaniController not displaying either QR or pin code

### ISSUE THREAD

**Issue by MySmilingTurban** [KhalisFoundation/sttm-desktop#1938]
Sync/BaniController not displaying either QR or pin code

https://github.com/KhalisFoundation/sttm-desktop/assets/51584037/14f8bf2e-76b2-4b35-8ea2-ea22e8cd02c5

Steps to reproduce
1. Open Sync/BaniController option, it does not show QR/Pincode even after long loading time

**Comment by Gauravjeetsingh** [comment]
Api was down, this should be fixed now.
