### ISSUE TITLE
9.2.2 (Win+MacOS) - Issue with Bani Contoller and Sangat Sync connection

### ISSUE THREAD

**Issue by MySmilingTurban** [KhalisFoundation/sttm-desktop#1976]
On putting code and pin, Bani Contoller shows endless loading.
Sangat Sync shows code is invalid even after multiple tries with different sync codes.

**Comment by Gauravjeetsingh** [comment]
This is because, sttm-web is using production API even on staging. While sttm-desktop alpha build uses dev API. I will see if we can update link in sttm-web for this.

**Comment by MySmilingTurban** [comment]
fixed in latest release
