### ISSUE TITLE
Allow copy paste in announcements box

### ISSUE THREAD

**Issue by ManjotS** [KhalisFoundation/sttm-desktop#1979]
<div> Freshdesk Ticket ID: <a href="https://khalis.freshdesk.com/a/tickets/7833">7833</a></div>
                       <div> Freshdesk Ticket Agent: Aman Singh</div>
                       <div> Freshdesk Ticket Agent Email: saintsoldierx@gmail.com</div>
                       <div> Ticket Priority: Low</div>
                       <div> Freshdesk Ticket Description: </div><div dir="ltr">
<div>On the desktop app, it would be nice if you could paste things into the announcements box instead of being forced to always type things out.</div>
<div><br></div>
<div>Thank you </div>
</div>

**Comment by ManjotS** [comment]
<div>Agent Aman Singh linked Freshdesk ticket <a href="https://khalis.freshdesk.com/a/tickets/7833">7833</a> for this issue.</div>

**Comment by yadvirkaur** [comment]
It's working in production app.

**Comment by Gauravjeetsingh** [comment]
Closing this out, thank you @yadvirkaur
