### ISSUE TITLE
Search box does not minimize in Single View

### ISSUE THREAD

**Issue by ManjotS** [KhalisFoundation/sttm-desktop#1984]
<div> Freshdesk Ticket ID: <a href="https://khalis.freshdesk.com/a/tickets/7845">7845</a></div>
                       <div> Freshdesk Ticket Agent: Aman Singh</div>
                       <div> Freshdesk Ticket Agent Email: saintsoldierx@gmail.com</div>
                       <div> Ticket Priority: Low</div>
                       <div> Freshdesk Ticket Description: </div><div>Waheguru ji ka Khalsa Waheguru ji ki Fateh
In Single-Display window, it is not possible to hide the small window (search, history) at the bottom right corner and it cover the text on the main window. Previous version was ok</div>

**Comment by ManjotS** [comment]
<div>Agent Aman Singh linked Freshdesk ticket <a href="https://khalis.freshdesk.com/a/tickets/7845">7845</a> for this issue.</div>

**Comment by Gauravjeetsingh** [comment]
This is fixed already, but its not released to production yet, @themanjotsingh veerji, can you test if this still happens on the latest beta release?
Windows: https://s3-us-west-2.amazonaws.com/sttm-releases/win-x64/SikhiToTheMaxSetup-9.2.2-beta.7.exe
Mac: https://s3-us-west-2.amazonaws.com/sttm-releases/mac-x64/SikhiToTheMax+Beta-9.2.2-beta.6.dmg
