### ISSUE TITLE
Multi-Pane Issue when opening ADV

### ISSUE THREAD

**Issue by themanjotsingh** [KhalisFoundation/sttm-desktop#1990]
I'm having issues with the multi-pane view, with Assa Dee Vaar.

There are no issues with opening multiple shabads. With a shabad in 1 and a shabad in 2, I am able to go back and forth between the pangtis.

When opening Assa Dee Vaar in 1, and a shabad in 2, I am not able to change to pangtian from Assa Dee Vaar. It shows the last line I changed to in 2. I can continue to change lines in 2 as it's not frozen, just not going to 1. If I search and open a shabad in 1, that will continue to work without issue. 

When adding a shabad into the 3rd pane, I was able to switch between that and the shabad in 2, but when clicking on a line in pane 1, the entire window went black.

**Comment by Gauravjeetsingh** [comment]
This is fixed already, but its not released to production yet, @themanjotsingh veerji, can you test if this still happens on the latest beta release?
Windows: https://s3-us-west-2.amazonaws.com/sttm-releases/win-x64/SikhiToTheMaxSetup-9.2.2-beta.7.exe
Mac: https://s3-us-west-2.amazonaws.com/sttm-releases/mac-x64/SikhiToTheMax+Beta-9.2.2-beta.6.dmg

**Comment by themanjotsingh** [comment]
Thank you veerjee, in the new beta the issue is resolved!
