### ISSUE TITLE
Presenter screen preferences

### ISSUE THREAD

**Issue by tarunsingh5** [KhalisFoundation/sttm-desktop#20]
This ticket is being repurposed for the task of bringing back the preferences screen. Should look exactly like it did before. (but in a new popup)

Presenter prefs: Need Dyanmic Setting to Change Font Size, Text Color, Background Color, Hide Lines, and Larivaar ... see mockup

show slide preview with ratio sliders for sizes next to it (should always = 100%).. checkbox for on off
Add background changer here STTME-4
Add theme changer as well
![image](https://user-images.githubusercontent.com/35271830/34891361-2abbdda8-f78a-11e7-879e-0bdd1c5129d5.png)

**Comment by ManjotS** [comment]
I think point is to have a new settings screen that isn't in the tiny
navigator.

**Comment by tarunsingh5** [comment]
i think this is obsolete given new UI work

**Comment by ManjotS** [comment]
this ticket addresses the new work

**Comment by tarunsingh5** [comment]
this mockup is very different than the current agreed upon work - leaving closed
