### ISSUE TITLE
Register  filetype and url schema

### ISSUE THREAD

**Issue by ManjotS** [KhalisFoundation/sttm-desktop#201]
When the app installs  it  should  register .sttm  files to  itself as well as banidb:// scheme.

The sttm files would contain json. We  will start with the ability to do file->save as

This would save json structure of  the currently loaded deck (bani/shabad  id etc)

banidb://  schema could  be  used  later for other things.

**Comment by prebhdevsingh** [comment]
why do we want users to have the option to save as json? Doesn't seem intuitive unless the user is an advanced user. LMK what problem we are trying to solve here.
