### ISSUE TITLE
Handle "address in use" error more gracefully

### ISSUE THREAD

**Issue by navdeepsinghkhalsa** [KhalisFoundation/sttm-desktop#206]
When another app is using port 1397, an error is shown whereas app should probably just look for another port

**Comment by navdeepsinghkhalsa** [comment]
![82238e4b-20c2-4e91-ad44-09ae9a66a6ea](https://user-images.githubusercontent.com/23178470/42984599-300c9142-8ba2-11e8-91f1-3f57589a75df.jpeg)

**Comment by tarunsingh5** [comment]
@lbk003 is this something you could work on?

**Comment by lbk003** [comment]
Looking @tarunsingh5

**Comment by tsingh777** [comment]
fixed by https://github.com/KhalisFoundation/sttm-desktop/pull/227
