### ISSUE TITLE
Use redux for state management

### ISSUE THREAD

**Issue by navdeepsinghkhalsa** [KhalisFoundation/sttm-desktop#207]
This is to replace the custom-built `Store` class for preferences as well as state management between search results, current, and history views. It will make for a more predictable process when dealing with data

Store in main process

- [ ] Store
- [ ] Search
- [ ] Results
- [ ] Viewer

**Comment by maneetpaul** [comment]
@tsingh777 do we still need this ticket?

**Comment by inderpreetsingh** [comment]
@maneetpaul we have moved to easy-peasy instead of redux for state management but we are still using custom store class for user preferences. So this ticket is partially done. 

`replace the custom-built Store class for preferences as well as state management `

**Comment by prebhdevsingh** [comment]
@inderpreetsingh is this still open?
