### ISSUE TITLE
Better handling of longer lines on overlay

### ISSUE THREAD

**Issue by navdeepsinghkhalsa** [KhalisFoundation/sttm-desktop#209]
Gurbani line gets cut off when translation is long
![0748bc54-323b-4900-b219-ed31e4f3dca5](https://user-images.githubusercontent.com/23178470/43025325-27245518-8c26-11e8-92c8-e41660ac80cf.png)

**Comment by tarunsingh5** [comment]
@navdeepsinghkhalsa i think #210 addresses this by allowing you to resize - should we close this out?

**Comment by maneetpaul** [comment]
I am going to close this. We have a few overlay tickets open so we can address this in another issue if needed. However, I think this has been resolved.
