### ISSUE TITLE
Ability to push only changed items in db as an update

### ISSUE THREAD

**Issue by tarunsingh5** [KhalisFoundation/sttm-desktop#21]
Prioritized as highest only so it can be moved to ShabadOS github.

We should make sure we apply db updates as sql updates rather than full blown downloads of the db every time we need to update. This will reduce the size of updates and use less data for users on the phones/pads etc. If something major is changing, then an exception to this rule is fine.

**Comment by ManjotS** [comment]
This ticket pertains to desktop pulling changes from the API. Please don't
assign to me.

**Comment by ManjotS** [comment]
API supports this now, desktop should implement.
