### ISSUE TITLE
Add sttm logo to overlay

### ISSUE THREAD

**Issue by ManjotS** [KhalisFoundation/sttm-desktop#211]
make it non intrusive (maybe square logo?) and have a checkbox to disable

**Comment by tsingh777** [comment]
how's this:
![image](https://user-images.githubusercontent.com/2982784/43179193-40a0edcc-8f86-11e8-849c-32664f3ffcba.png)

**Comment by ManjotS** [comment]
Think TV logos... like CNN..

Logo shouldnt be faded when its on a bar (you can  do the transparent thing if it was the only thing over video, otherwise do 100% opacity)

Text should have a margin and not overlay the logo.

By the way, we should also take overscan into consideration for the overlay in general:

https://www.engadget.com/2010/05/27/hd-101-overscan-and-why-all-tvs-do-it/

AFAIK, you want at least 5% margin all the way around. In the TV industry, title safe, or whats considered safe area to add overlays and titles is 7.5%

**Comment by tsingh777** [comment]
For overscan, OBS should handle that. The user can just resize the overlay so it fits where it needs to. STTM should just generate what needs to go there.

The can't figure how to make this logo look nice. Trying to keep it static and it looks like crap when the bar height changes. I don't know if we want to keep it in the bar either since the bar can be positioned just at the bottom, just at the top, or split. More than likely no one will want it on... 

Can i get a mockup of how it should behave?

**Comment by ManjotS** [comment]
This is what I would start with:

![image](https://user-images.githubusercontent.com/644885/43484662-d80c4d54-94c3-11e8-9dc5-1faea57db502.png)

![image](https://user-images.githubusercontent.com/644885/43484687-e45b28aa-94c3-11e8-895a-b3bf466e6ce2.png)

![image](https://user-images.githubusercontent.com/644885/43484693-e7cf7a9a-94c3-11e8-9c89-57ceb07eb612.png)

margins and opacity should be under user control (probably in OBS)

**Comment by maneetpaul** [comment]
@inderpreetsingh I know you are working on this one. 

A subtle approach like how we have the "SikhiToTheMax" branding on every theme at the bottom left would be appropriate as well. 

@saintsoldierx can you provide some input here?

**Comment by saintsoldierx** [comment]
![image](https://user-images.githubusercontent.com/27791330/68826361-6f24f780-0652-11ea-870c-2338f68e2bb8.png)
i'm thinking more like this..

**Comment by saintsoldierx** [comment]
![image](https://user-images.githubusercontent.com/27791330/68826510-17d35700-0653-11ea-81ee-53722d6ed016.png)

**Comment by saintsoldierx** [comment]
![image](https://user-images.githubusercontent.com/27791330/68826865-89f86b80-0654-11ea-85fc-f17c44aeea5b.png)

**Comment by saintsoldierx** [comment]
![image](https://user-images.githubusercontent.com/27791330/68827365-8d8cf200-0656-11ea-9cb2-a22316c534e1.png)

**Comment by saintsoldierx** [comment]
![sttm-logo-watermark](https://user-images.githubusercontent.com/27791330/68882948-f7dc7b80-06c4-11ea-9c58-0cb009fa7b52.png)
![sttm-logo-watermark - white](https://user-images.githubusercontent.com/27791330/68883031-18a4d100-06c5-11ea-8419-3264b8f0f830.png)
Two logos attached, 200px in width. I would say add the white BG box using CSS.

**Comment by saintsoldierx** [comment]
(You may not see the white logo above due to white background :) )
