### ISSUE TITLE
Change overlay default port number to 1469

### ISSUE THREAD

**Issue by lbk003** [KhalisFoundation/sttm-desktop#221]
Currently the overlay default port number in the overlay url is 1397

Can we change it to 1469 🙏 ?
Do users book mark that url? Would it break anything if it were upgraded?

**Comment by navdeepsinghkhalsa** [comment]
Both numbers are significant. 1469 goes without saying. @inderpreetsingh proposed 1397 for when it's read in Punjabi: ਤੇਰਾ ਨਾਂ ਸਤਿ

**Comment by tarunsingh5** [comment]
is this necessary given the new cycling through ports?

**Comment by tsingh777** [comment]
probably not.
