### ISSUE TITLE
Incorrect command to build for package on mac

### ISSUE THREAD

**Issue by lbk003** [KhalisFoundation/sttm-desktop#222]
The [Readme.md](https://github.com/KhalisFoundation/sttm-desktop/blob/master/README.md) file on github has an incorrect command

`npm run pack:osx`

results in the following error

> missing script: pack:osx

**Comment by lbk003** [comment]
BTW,
`npm run pack:mac` also has an error on `master` branch

**Comment by tsingh777** [comment]
https://github.com/KhalisFoundation/sttm-desktop/pull/310
