### ISSUE TITLE
Switching between shabads

### ISSUE THREAD

**Issue by singh-harshdeep** [KhalisFoundation/sttm-desktop#232]
User is presenting two shabads: A and B. After getting to line "4" in shabad A, the ragi switches to Shabad B. When going back to Shabad A, the presenter should only switch back to a specific line in Shabad A (line 4) until the user physically selects it (line 4).  Until then the presenter should continue to display the recent pangti from Shabad B. 

As of now, when a user attempts to go back to line "4" in shabad A, the presenter displays the default line "1" before the change is made - confuses the sangat.

**Comment by maneetpaul** [comment]
This was completed with our history updates.
