### ISSUE TITLE
presenter view when casting in new UI not correct size

### ISSUE THREAD

**Issue by tarunsingh5** [KhalisFoundation/sttm-desktop#234]
see screenshot

<img width="1674" alt="screen shot 2018-08-07 at 10 41 08 pm" src="https://user-images.githubusercontent.com/35271830/43818458-aa7e618a-9a93-11e8-83ed-7d1ba92c328f.png">

**Comment by inderpreetsingh** [comment]
Fixed. Sent pull request #237
