### ISSUE TITLE
fonts in search results small in new UI

### ISSUE THREAD

**Issue by tarunsingh5** [KhalisFoundation/sttm-desktop#236]
see screenshot

**Comment by tarunsingh5** [comment]
<img width="1678" alt="screen shot 2018-08-07 at 10 43 25 pm" src="https://user-images.githubusercontent.com/35271830/43818531-f2c74b1e-9a93-11e8-8407-56992f0f7537.png">

**Comment by tarunsingh5** [comment]
@inderpreetsingh can you take this on?

**Comment by inderpreetsingh** [comment]
@tarunsingh5 umm little confused on which font-size are you talking about? I compared the current shabad, and search result font-sizes with master, they are same. May be I am missing something, can you please explain it a little.

**Comment by tarunsingh5** [comment]
ah ok maybe i was just finding it hard to read on a different screen - closing for now
