### ISSUE TITLE
Show shortcuts cheatsheet in settings

### ISSUE THREAD

**Issue by tarunsingh5** [KhalisFoundation/sttm-desktop#24]
Will map shortcut cheat sheet to Ctrl+/ (PC) or Cmd+/ (Mac) and put a link in the Help menu

**Comment by tarunsingh5** [comment]
@saintsoldierx can you work with @irvanjit on this

**Comment by saintsoldierx** [comment]
@AkalUstat has worked on this one I believe.

**Comment by AkalUstat** [comment]
@saintsoldierx i was thinking of remapping some of the shortcuts to some other buttons. I'll have a preliminary draft by the end of today and send it to you and @maneetpaul bhai sahib to review.

**Comment by AkalUstat** [comment]
Ok @saintsoldierx so I talked to @tsingh777 at hackathon and he said that all our help guides are in the help guide, so i didn't added the Shortcut Legend to the 'other section'
