### ISSUE TITLE
Add display options tab in new UI

### ISSUE THREAD

**Issue by inderpreetsingh** [KhalisFoundation/sttm-desktop#240]
Add these options in a tab
<img width="373" alt="displayoptions" src="https://user-images.githubusercontent.com/1131610/43888671-dae31738-9bdf-11e8-858a-d84b246653ef.png">

**Comment by inderpreetsingh** [comment]
Assigning this to @gauravjeet singh veerji 🙏

**Comment by tarunsingh5** [comment]
confirming this was pushed in 4.1
