### ISSUE TITLE
In linux, the minimized icon comes in the second row.

### ISSUE THREAD

**Issue by Gauravjeetsingh** [KhalisFoundation/sttm-desktop#244]
Looks fine on mac and windows, only on a Linux system it comes in a second row

![screenshot from 2018-08-10 21-58-54](https://user-images.githubusercontent.com/1990932/43969763-c5f88aec-9ce8-11e8-8018-c5c2366e0482.png)
.

**Comment by prebhdevsingh** [comment]
@inderpreetsingh is this still an issue with the latest UI and improvements?
