### ISSUE TITLE
Prevent 'Bani Overlay' from opening multiple times 

### ISSUE THREAD

**Issue by maneetpaul** [KhalisFoundation/sttm-desktop#246]
![screen shot 2018-08-10 at 11 33 53 pm](https://user-images.githubusercontent.com/10658257/43987863-229a5354-9cf6-11e8-8a27-1d18a6761fac.png)
![screen shot 2018-08-10 at 11 05 42 pm](https://user-images.githubusercontent.com/10658257/43987864-2514a1e8-9cf6-11e8-87b0-6ee4dabf330d.png)

**Comment by tsingh777** [comment]
Seems to be the case for other windows as well (help, change log, notifications). 

will fix it for all.

**Comment by tsingh777** [comment]
https://github.com/KhalisFoundation/sttm-desktop/pull/247
