### ISSUE TITLE
Minimizing search window in non-presenter view hides expand button

### ISSUE THREAD

**Issue by tsingh777** [KhalisFoundation/sttm-desktop#249]
![min](https://user-images.githubusercontent.com/2982784/44003597-a5ce3d6c-9e09-11e8-8349-65be50e6aa5a.gif)

**Comment by tsingh777** [comment]
https://github.com/KhalisFoundation/sttm-desktop/pull/272

**Comment by tarunsingh5** [comment]
confirming this has been fixed in 4.1
