### ISSUE TITLE
add ability to load full shabad, ashtpadi, ang, bani, or raag

### ISSUE THREAD

**Issue by tarunsingh5** [KhalisFoundation/sttm-desktop#25]

**Comment by navdeepsinghkhalsa** [comment]
Could these please be broken up into separate issues? Ang search will be coupled with #23

**Comment by sukhpalsingh** [comment]
added #418 for adding baani view and starting working on it. Please let me know if anyone else is working on this part already so that i don't repeat the same task. Thanks

**Comment by maneetpaul** [comment]
Closing this as we have achieved most of this via Sundar Gutka and will continue adding features that relate to this.

**Comment by ManjotS** [comment]
I think we should keep this open as there will be a similar feature on web.
Its really a database issue for different sized shabads.
