### ISSUE TITLE
text cut off on 4:3

### ISSUE THREAD

**Issue by ManjotS** [KhalisFoundation/sttm-desktop#251]
![screen shot 2018-08-13 at 9 14 05 am](https://user-images.githubusercontent.com/644885/44044056-44a859fc-9ed9-11e8-9870-5ab3002d3648.png)

**Comment by ManjotS** [comment]
![screen shot 2018-08-13 at 9 17 45 am](https://user-images.githubusercontent.com/644885/44044223-c21febd4-9ed9-11e8-91d2-fcf88b7f3fc0.png)

**Comment by ManjotS** [comment]
Seeing this issue  at  gurdwaras with  4:3 projectors (most  of them)

**Comment by inderpreetsingh** [comment]
![image](https://user-images.githubusercontent.com/1131610/47014957-5b664380-d169-11e8-8988-de6a649f75f6.png)

It is not being cut off from side but it gets cut from below.

**Comment by inderpreetsingh** [comment]
However that happens everywhere (in all resolutions) 🐛 

![image](https://user-images.githubusercontent.com/1131610/47015014-8355a700-d169-11e8-98c1-15446729dfb5.png)
