### ISSUE TITLE
quick tools displace text instead of appearing over it

### ISSUE THREAD

**Issue by ManjotS** [KhalisFoundation/sttm-desktop#254]
This doesnt allow accurate changing.

![screen shot 2018-08-14 at 2 39 58 pm](https://user-images.githubusercontent.com/644885/44120111-229c79ea-9fd0-11e8-8d2d-c4ac2cee976a.png)
![screen shot 2018-08-14 at 2 40 04 pm](https://user-images.githubusercontent.com/644885/44120112-22b7dc62-9fd0-11e8-8b32-b55f7f019530.png)

**Comment by tarunsingh5** [comment]
this is working as intended

**Comment by ManjotS** [comment]
then intended is buggy and it should be fixed. you cant accurately set size without being able to see it.

**Comment by tarunsingh5** [comment]
you cant do that if it overlaps either - this is p3 imo

**Comment by ManjotS** [comment]
you can if it overlaps, very easily. its transparent

**Comment by maneetpaul** [comment]
This was resolved.
