### ISSUE TITLE
scripture drop down dissappears when no results

### ISSUE THREAD

**Issue by ManjotS** [KhalisFoundation/sttm-desktop#256]
1. set scripture to bhai gurdas jee (not singh)
2. search vvgs
3. no results, scripture drop down is gone

I have to backspace my search and reset it to bhai gurdas singh or all and then type again to be able to find vaho vaho gobind singh

**Comment by tarunsingh5** [comment]
bhai gurdas singh is the correct author for the shabad you are looking for though...

**Comment by ManjotS** [comment]
yes, but the error is the drop down dissappears when theres no results for the selected scripture.

You cant change to the correct scripture, because the drop down is gone.

**Comment by tsingh777** [comment]
I have a PR that changes how scripture filter works a bit. See https://github.com/KhalisFoundation/sttm-desktop/pull/242

**Comment by tsingh777** [comment]
@ManjotS is this still valid? 

Scripture drop down will only disappear when All sources are selected and no results are returned as per @inderpreetsingh & @saintsoldierx .

**Comment by saintsoldierx** [comment]
@maneetpaul i dont think this is an issue anymore...?

**Comment by maneetpaul** [comment]
Confirmed no longer issue
