### ISSUE TITLE
autoplay toggle does nothing with no error

### ISSUE THREAD

**Issue by ManjotS** [KhalisFoundation/sttm-desktop#259]
1. search for a shabad
2. open the shabad
3. go to settings
4. click autoplay
5. toggle just flashes

**Comment by tarunsingh5** [comment]
can you please provide a video?

**Comment by ManjotS** [comment]
![autoplay](https://user-images.githubusercontent.com/644885/44120973-fd6615e8-9fd2-11e8-8cd1-b560ffa1c254.gif)

**Comment by tsingh777** [comment]
since it only makes since with Akhand Paatth View, I think we need to disable it unless APV is on.

**Comment by ManjotS** [comment]
Why can't we auto cycle slides.

**Comment by lbk003** [comment]
@maneetpaul  What is the expected behavior for the autoplay function? Please clarify.

**Comment by inderpreetsingh** [comment]
I can't reproduce it 🤔

**Comment by inderpreetsingh** [comment]
I am able to reproduce it in build. 🙏

**Comment by prebhdevsingh** [comment]
I can see this potentially causing issues with auto-advancing slides during kirtan if someone switches back from the AP mode. I'd rather just hide the setting or provide an indication that this option only works w/ AP mode.

**Comment by Gauravjeetsingh** [comment]
working in latest release, closing this out.
