### ISSUE TITLE
add overlay window somewhere within UI or settings

### ISSUE THREAD

**Issue by ManjotS** [KhalisFoundation/sttm-desktop#262]
It should also be in the same place as the live feed text files. Intuitively they should be available in similar places.

**Comment by tarunsingh5** [comment]
i dont agree w/ this - overlay is an advanced setting - its ok to be in the menu

**Comment by ManjotS** [comment]
maybe we should move the live feed text files to the top too

**Comment by tarunsingh5** [comment]
lets move this to a 4.2 milestone

**Comment by maneetpaul** [comment]
We are revamping the overlay window and will make it more accessible.
