### ISSUE TITLE
overlapping text when some fields are hidden

### ISSUE THREAD

**Issue by tarunsingh5** [KhalisFoundation/sttm-desktop#263]
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/35271830/44130775-f250e878-a003-11e8-9186-bfa9dfed7f6b.gif)

**Comment by tsingh777** [comment]
This happens when we have some fields hidden (teeka, translation, translit). The css to hide the line happens after it is populated. 

Will take a look.

**Comment by tsingh777** [comment]
@inderpreetsingh can you help here?

When we call `line.classList.add('active');` in viewer.js on line 306 (https://github.com/KhalisFoundation/sttm-desktop/blob/dev/www/js/viewer.js#L306) the active card shows all the text and then hides it after a little while. Pretty sure it's css related. You are more familiar with this, can you take a look?

**Comment by tarunsingh5** [comment]
@inderpreetsingh any update here?

**Comment by inderpreetsingh** [comment]
@tarunsingh5 haven't gotten chance to look at this yet. I will try to get this done tonight.

**Comment by tarunsingh5** [comment]
fixed in 4.1
