### ISSUE TITLE
Unable to stop casting from windows

### ISSUE THREAD

**Issue by inderpreetsingh** [KhalisFoundation/sttm-desktop#264]
After successful casting, the cast menu still has "Search for cast device" option which opens the "list of casting devices" modal.

**Comment by maneetpaul** [comment]
@inderpreetsingh Was this pushed in 4.1 release?

**Comment by inderpreetsingh** [comment]
@maneetpaul hanji veerji https://github.com/KhalisFoundation/sttm-desktop/pull/277

**Comment by inderpreetsingh** [comment]
*Works successfully on windows*

![image](https://user-images.githubusercontent.com/1131610/47014591-4ccb5c80-d168-11e8-9a33-a42767a138fd.png)

![image](https://user-images.githubusercontent.com/1131610/47014616-6371b380-d168-11e8-9916-1ecf537be1f2.png)
