### ISSUE TITLE
An asterisk when searching should check for shabads using all characters 

### ISSUE THREAD

**Issue by maneetpaul** [KhalisFoundation/sttm-desktop#268]
Example: you are searching for a shabad and you are unsure if the letter is a V or a B. Typing a "space" would check against all characters in that place. 

* [x] First letter search Anywhere
* [x] First letter search start

**Comment by ManjotS** [comment]
I would prefer we use standard search engine operators, such as asterisk.

**Comment by maneetpaul** [comment]
Agreed. Edited title to reflect.

**Comment by inderpreetsingh** [comment]
Got it working for Search Anywhere, trying to make it work for search start

**Comment by ManjotS** [comment]
Asterisk at front should auto change to anywhere.

**Comment by tarunsingh5** [comment]
@inderpreetsingh any update on getting it to work for start?

**Comment by tarunsingh5** [comment]
@navdeepsinghkhalsa can you do this for realm?

**Comment by inderpreetsingh** [comment]
@tarunsingh5 i think i tagged only in PR and forgot to comment here but it worked for search start as well. 🙏
