### ISSUE TITLE
add keyboard shortcuts

### ISSUE THREAD

**Issue by tarunsingh5** [KhalisFoundation/sttm-desktop#27]
Bind number keys 1,2,3,4 etc. with each stanza. Pressing number keys should take you to that specific stanza.
Space bar = jump to the panktee you searched for
Space bar again goes to next stanza (ie. if kirtanis just finished reading 4th stanza, pressing space bar will take you to panktee that was searched for, pressing spacebar again will take you to beginning of 5th stanza)
Home key also takes you to panktee that you searched for

**Comment by tarunsingh5** [comment]
so i think space bar should only be mapped to one action - it is too confusing otherwise

**Comment by sukhpalsingh** [comment]
I agree with @tarunsingh5  that one key should be mapped to one action. I did implemented an approach earlier in another project to do the similar tasks as suggested earlier. What i did was as follows:

left arrow for previous pankti.
right arrow for next pankti.
up arrow for the home pankti (the pankti you searched before).
down arrow will auto navigate the pankti in the following way:

pressing down first time after the search will move to the first pankti.
pressing down each time will navigate to the next pankti.
pressing home will go to home pankti and also will remember the pankti that you were on.
pressing down after home will go to the next pankti after the last remembered pankti.

I found this was really the way you actually navigate in the real example when listening to Gurbani.

**Comment by sukhpalsingh** [comment]
sure i will take this one.

**Comment by sukhpalsingh** [comment]
can someone please add me to this project so that i can assign the issue to myself?

**Comment by prebhdevsingh** [comment]
Yes, let me ask one of the admins. Will you be able to join our Slack?

**Comment by sukhpalsingh** [comment]
thanks. let me know where to join Slack so that i can join you guys there.

**Comment by ManjotS** [comment]
@sukhpalsingh we need your email to invite you, can you hit our contact form on khalisfoundation.org and send your email?

**Comment by sukhpalsingh** [comment]
sent. thanks

**Comment by tarunsingh5** [comment]
@sukhpalsingh any update here?

**Comment by maneetpaul** [comment]
Some of this has already been worked on. Going to close and work on in future tickets.

**Comment by ManjotS** [comment]
@maneetpaul can you investigate the gap between current keyboard shortcuts and what would be nice have and ticket it?
