### ISSUE TITLE
Keertanyee Confidence Monitor

### ISSUE THREAD

**Issue by maneetpaul** [KhalisFoundation/sttm-desktop#276]
Often times keertanyees have a monitor or iPad located directly in front of them to showcase the shabad they are reading. 

Requirements: 

- Should be connected to the single STTM instance 
- Compatible with all types of devices (tablets, phones, computer connected to a display, etc)

In terms of UI, some suggestions that were discussed on Slack: 

- Large text centered on the screen
- Show previous and next line with a slightly lower opacity. Maybe an option to show every line as well.

**Comment by maneetpaul** [comment]
@saintsoldierx if you can provide some more UI input or a potential mock-up, I'm sure that would be helpful

**Comment by ManjotS** [comment]
Aman Singh [Yesterday at 8:16 AM]
My vision of that is also to have it connected to the single STTM instance being used for live and projector, but to have it more simplified for Keertani - ie. large Gurbani only in middle of screen with previous tukk and next tukk on the same screen, smaller font and lower opacity.

Manjot Singh [23 hours ago]
second chromecast could do it too
or usb hdmi

Aman Singh [23 hours ago]
or another server with HTML…?

Manjot Singh [23 hours ago]
but that requires another machine/phone
id say all  of the above

Manjot Singh [23 hours ago]
could  also be done with presenter  mode  off and one screen is keertani  view and second is projector

Manjot Singh [23 hours ago]
thanks

**Comment by ManjotS** [comment]
- [ ] Add keertani mode (like AP mode,  may require mode selection interface)
- [ ] Allow more than one mode at a time
- [ ] Keertani mode should have 2 options: full scrollable paragraph (like AP mode) or large Gurbani only in middle of screen with previous tukk and next tukk on the same screen, smaller font and lower opacity.
- [ ] Allow second chromecast for keertani window
- [ ] Create  html server for keertani  window to show on  another  device
- [ ] Allow different mode per  screen with extended desktop(s)

**Comment by maneetpaul** [comment]
Sangat sync achieves this. Closing.
