### ISSUE TITLE
Tabs should show based on size 

### ISSUE THREAD

**Issue by tsingh777** [KhalisFoundation/sttm-desktop#279]
Follow up of https://github.com/KhalisFoundation/sttm-desktop/pull/243
>there's space on the right hand side, I think there should be no select at all. It's only when there's no space on right hand side, and the box is small, only then we should have that dropdown. That will also show selectbox at only edge cases (small screens) and we might tolerate that.

![image](https://user-images.githubusercontent.com/2982784/44438457-04326100-a574-11e8-9dbc-d041967016b8.png)

**Comment by maneetpaul** [comment]
To be addressed in #280
