### ISSUE TITLE
Display Options UI Enhancements

### ISSUE THREAD

**Issue by trimankandola** [KhalisFoundation/sttm-desktop#280]
![image](https://user-images.githubusercontent.com/20653829/44484586-2d0e3100-a61c-11e8-964d-9829f67aa556.png)

**Comment by saintsoldierx** [comment]
Please remove from the top left settings and leave in the bottom right panel.

**Comment by maneetpaul** [comment]
Spoke with @saintsoldierx  - see notes below: 

- Move EVERYTHING that is currently in "Preferences" to the "Display Options" tab in the bottom right quadrant of presenter view 
- When somebody goes to "File > Preferences" or presses the keyboard shortcut "Command +," it should go to the "Display Options" tab in the bottom right, we are eliminating the "Settings" menu completely when in Presenter View
- Additionally, remove the dropdown for "Other" in the bottom right quadrant and make it it's own tab next to "Display Options" 

@inderpreetsingh Let us know if this needs any further clarification

**Comment by tsingh777** [comment]
@maneetpaul @saintsoldierx 
> Additionally, remove the dropdown for "Other" in the bottom right quadrant and make it it's own tab next to "Display"
I believe this was done to because we can't fit all the tabs at the top of the box. Think the change here would be how we show extra tabs.

**Comment by maneetpaul** [comment]
Yes for the non-presenter view we should keep the drop-down. But for presenter view, it should be a stand-alone tab.

**Comment by maneetpaul** [comment]
Closing this. Going to address this in a more solidified plan for UI fixes in a future release. Creating a separate issue to address the "Others" as a standalone tab.
