### ISSUE TITLE
Refreshing App with second screen connected loads in non Presenter view with presenter view toggle still enabled

### ISSUE THREAD

**Issue by tsingh777** [KhalisFoundation/sttm-desktop#286]
Steps to reproduce. 

- Have second screen connected
- Be in presenter view 
- Refresh the app (command+R mac)
- You will see this below:

![image](https://user-images.githubusercontent.com/2982784/44590134-3c51c380-a76f-11e8-8782-8a8efacebf4f.png)

**Comment by prebhdevsingh** [comment]
@Gauravjeetsingh @tsingh777 can you please check if this is still an issue?

**Comment by Gauravjeetsingh** [comment]
Not an issue in latest release, closing this out.
