### ISSUE TITLE
& not showing on update dialogue on Windows

### ISSUE THREAD

**Issue by navdeepsinghkhalsa** [KhalisFoundation/sttm-desktop#290]
Should either look at escaping the character or replace with "and" if not possible

Win7
<img width="412" alt="win7" src="https://user-images.githubusercontent.com/23178470/44692123-595bf000-aa16-11e8-83ec-8daa13e4f035.png">

Win10
<img width="476" alt="win10" src="https://user-images.githubusercontent.com/23178470/44692128-5d880d80-aa16-11e8-86e1-27437b007201.png">

**Comment by maneetpaul** [comment]
For reference, this is what it suppose to look like: 

<img width="532" alt="screen shot 2018-09-03 at 4 34 59 pm" src="https://user-images.githubusercontent.com/10658257/45002257-e9fc7800-afa2-11e8-9716-e08b220af636.png">

**Comment by inderpreetsingh** [comment]
![image](https://user-images.githubusercontent.com/1131610/47017045-d847ec00-d16e-11e8-81cb-96ab3900b459.png)
