### ISSUE TITLE
next line toggle not working on 4.1 on Windows

### ISSUE THREAD

**Issue by tarunsingh5** [KhalisFoundation/sttm-desktop#292]

**Comment by maneetpaul** [comment]
@inderpreetsingh let us know how we can help

**Comment by inderpreetsingh** [comment]
*QA*

![sttm-292](https://user-images.githubusercontent.com/1131610/47014363-af702880-d167-11e8-92e8-9185adfd1353.gif)

**Comment by inderpreetsingh** [comment]
![image](https://user-images.githubusercontent.com/1131610/47014591-4ccb5c80-d168-11e8-9a33-a42767a138fd.png)

![image](https://user-images.githubusercontent.com/1131610/47014616-6371b380-d168-11e8-9916-1ecf537be1f2.png)
