### ISSUE TITLE
500ms debounce causing program to feel slow and unresponsive in 4.1

### ISSUE THREAD

**Issue by tarunsingh5** [KhalisFoundation/sttm-desktop#293]
are debouncing just clicking on a shabad or everything?

**Comment by tsingh777** [comment]
The debounce is on the leading edge so It shouldn't cause anything. Is the slowness/unresponsiveness consistent?

**Comment by ManjotS** [comment]
whats happening is the 500ms is also delaying lines showing in "current shabad window" whereas it should only affect search click action.

**Comment by ManjotS** [comment]
we decided on the call  to remove  debounce and instead have shabad load clear current shabad in the load function.

**Comment by tsingh777** [comment]
should be fixed by https://github.com/KhalisFoundation/sttm-desktop/pull/299

**Comment by inderpreetsingh** [comment]
Checked on windows, didn't find any lag. 👍

**Comment by tarunsingh5** [comment]
confirming no double load and no lag on mac
