### ISSUE TITLE
Update help for new UI

### ISSUE THREAD

**Issue by tsingh777** [KhalisFoundation/sttm-desktop#294]
The guide might be a little out of date now. It will probably need new screenshots.

**Comment by maneetpaul** [comment]
Change _How do I change the background color?_ to: 

How do I change the background or font color?

- STTM comes pre-loaded with several themes beautifully designed for displaying Gurbani. After launching STTM, click "Themes" in the bottom right of Presenter View to choose one that suits your environment. 
![themes](https://user-images.githubusercontent.com/10658257/46249369-36967000-c3f6-11e8-9fa5-f02726bd454a.png)

**Comment by maneetpaul** [comment]
Change _How can I make the fonts on the screen smaller?_ to: 

How can I adjust the font size or what is displayed on the screen?

After launching STTM, click the icon for settings, and scroll down for options to adjust the font size.
<img width="654" alt="desktop-font-size" src="https://user-images.githubusercontent.com/10658257/46249427-229f3e00-c3f7-11e8-8d52-c2ac36410a52.png">

OR

Click the "Quick Tools" button to make adjustments: 
![quick tools](https://user-images.githubusercontent.com/10658257/46249440-419dd000-c3f7-11e8-971e-12850e54dc6c.png)

**Comment by maneetpaul** [comment]
Other changes pending #280
