### ISSUE TITLE
add presenter view toggle button to current shabad (single monitor only)

### ISSUE THREAD

**Issue by ManjotS** [KhalisFoundation/sttm-desktop#295]
maybe  to title or bottom right. This is useful in single monitor if you want to do search in presenter and then quickly switch to full slide.

perhaps @saintsoldierx can provide design and icon location guidance

**Comment by maneetpaul** [comment]
@ManjotS I'm not sure if I understand the use-case behind this. Would you be able to elaborate a bit?

**Comment by saintsoldierx** [comment]
I would like to see the UI for dual-monitor if I am using a single monitor. Because STTM isn't always for presentation, sometimes it's useful for doing research or when you don't have an internet connection like being on a plane.

**Comment by saintsoldierx** [comment]
![image](https://user-images.githubusercontent.com/27791330/45001623-55365200-af83-11e8-8f3e-3926590c01f0.png)

**Comment by ManjotS** [comment]
no, we  want it available for  both. There are cases  where you have 2
monitors but  only want one  for sttm (maybe  being used for overlays or
 kirtani view, which we talked about as possible upcoming feature)
