### ISSUE TITLE
Spacing when casting to device is not same as spacing in presenter view

### ISSUE THREAD

**Issue by JazSingh** [KhalisFoundation/sttm-desktop#301]
The spacing between the different types of lines (e.g. Gurmukhi, English translation and transliteration) is not the same when casting compared to the spacing in presenter view. When casting, everything aligns to the top rather than having the correct spacing.

**Comment by tarunsingh5** [comment]
same as #300

**Comment by tarunsingh5** [comment]
@tsingh777 can you take a stab at this? we are getting multiple tickets for it
