### ISSUE TITLE
Akhand Paatth View infinite loop

### ISSUE THREAD

**Issue by navdeepsinghkhalsa** [KhalisFoundation/sttm-desktop#307]
When Akhand Paatth View is on, loading a Shabad keeps loading more and more Angs without waiting for scroll

**Comment by maneetpaul** [comment]
Has this been merged to dev? @navdeepsinghkhalsa @tsingh777

**Comment by tsingh777** [comment]
waiting for review on https://github.com/KhalisFoundation/sttm-desktop/pull/320 by @navdeepsinghkhalsa and @saintsoldierx
