### ISSUE TITLE
Clear search field (new feature)

### ISSUE THREAD

**Issue by singh-harshdeep** [KhalisFoundation/sttm-desktop#319]
Would be convenient to have a button to clear the search field instead of having to backspace multiple times.

**Comment by maneetpaul** [comment]
This should probably be a keyboard shortcut

**Comment by ManjotS** [comment]
I think we need a little x in the input like we have on web. We’ve
discussed it on and off for years and it hasn’t happened.

**Comment by AkalUstat** [comment]
@maneetpaul i can have it so that the shortcut for the search bar also clears it

**Comment by maneetpaul** [comment]
CTRL + / shortcut clears search
