### ISSUE TITLE
Add donation section

### ISSUE THREAD

**Issue by tarunsingh5** [KhalisFoundation/sttm-desktop#32]

**Comment by inderpreetsingh** [comment]
@tarunsingh5 need more details. Do I need to integrate payment gateway? Are we on patreon?

**Comment by tarunsingh5** [comment]
please see how we did https://khalisfoundation.org/donate/

**Comment by tarunsingh5** [comment]
@ManjotS i believe @inderpreetsingh needs your help here w/ paypal

**Comment by tarunsingh5** [comment]
@inderpreetsingh can you add the link to donate to both the changelog and the guide

**Comment by tarunsingh5** [comment]
ideally we can have it pinned on the changelog and guide

**Comment by tarunsingh5** [comment]
launched
