### ISSUE TITLE
Bani Overlay - compact theme

### ISSUE THREAD

**Issue by saintsoldierx** [KhalisFoundation/sttm-desktop#324]
![image](https://user-images.githubusercontent.com/27791330/45923620-e8d2b280-be9f-11e8-8b2b-e36fc8edd703.png)
Create new theme for Bani Overlay called compact mode - this will allow for overlay with familiar, standard subtitling you would normally see on television etc.

Two options if possible - one should display static subtitles in multiple lines if the tukks are long. The other option could be to have only one line of Gurbani and if tukk is longer than the space allows, allow it to scroll horizontally using some JS.

**Comment by maneetpaul** [comment]
Replacing with #931
