### ISSUE TITLE
History should retain Shabad status

### ISSUE THREAD

**Issue by navdeepsinghkhalsa** [KhalisFoundation/sttm-desktop#329]
All read lines should remain checked when clicking back to a Shabad and last selected line should come up. This is useful when switching back from a Parmaan.

Should be implemented along with Redux

**Comment by maneetpaul** [comment]
This should also be the case for Banis (not just shabads)

**Comment by inderpreetsingh** [comment]
@maneetpaul veerji Not sure but I think this needs to be rescoped for after react and redux. 🙏

**Comment by maneetpaul** [comment]
@inderpreetsingh @tsingh777 @navdeepsinghkhalsa any way we can do this before the technical debt Sprint? Or would it not be worth it until after?
