### ISSUE TITLE
[4.2] Logo on Cast does not match preview screen

### ISSUE THREAD

**Issue by tarunsingh5** [KhalisFoundation/sttm-desktop#333]
the logo on the screen thats cast on the tv is not in the same position as the preview pane
the casted screen is slightly to the right
logo is also much larger on casted screen

**Comment by navdeepsinghkhalsa** [comment]
Which is expected behaviour? The one on Chromecast or preview pane?

**Comment by tarunsingh5** [comment]
i like the proportions of the preview one tbh

**Comment by maneetpaul** [comment]
Can this be closed?
