### ISSUE TITLE
Unable to use app when DB is downloading

### ISSUE THREAD

**Issue by maneetpaul** [KhalisFoundation/sttm-desktop#336]
When launching the app for the first time, the app is unusable when the DB is downloading.

**Comment by navdeepsinghkhalsa** [comment]
Techinical note: This is happening only when the file is being extracted. That action should probably be moved to the main process.

**Comment by tarunsingh5** [comment]
i was able to use the app but when the updated db finished downloading the entire app screen went white and the chromecast crashed - i cant recreate this since there isnt a new db available

**Comment by maneetpaul** [comment]
Recreated this issue when opening the new beta build for the first time. I did a search while it was updating the DB and when the green progress bar finished the whole app went white and I had to relaunch. 

![screen shot 2018-10-14 at 6 48 44 pm](https://user-images.githubusercontent.com/10658257/46923185-385d5780-cfe2-11e8-8713-4648b838ff7b.png)

**Comment by inderpreetsingh** [comment]
@saintsoldierx Maybe we should show a different kind of loader for this?

**Comment by tarunsingh5** [comment]
@navdeepsinghkhalsa i think that solution sounds like a reasonable stop gap to me - @maneetpaul any concerns?

**Comment by navdeepsinghkhalsa** [comment]
We decided to disable search during database update as a stopgap

**Comment by ManjotS** [comment]
Again I'm strongly against handicapping a working feature because we
introduced a bug.

**Comment by navdeepsinghkhalsa** [comment]
@ManjotS One option is to use Realm Cloud for database updates. Another is to fast track the API for our custom update mechanism

**Comment by ManjotS** [comment]
Full db update should still work even with api features. If realm cloud can
do that, then it's good.

Is there a cost?
