### ISSUE TITLE
Auto-scroll Akhand Patth View

### ISSUE THREAD

**Issue by tarunsingh5** [KhalisFoundation/sttm-desktop#34]
Provide controls to adjust speed

**Comment by tarunsingh5** [comment]
i think @inderpreetsingh is working on this?

**Comment by inderpreetsingh** [comment]
Yes, I have a PR for this https://github.com/KhalisFoundation/sttm-desktop/pull/98

**Comment by navdeepsinghkhalsa** [comment]
While #98 is merged, I don't think that applies to APV. This is a separate issue
