### ISSUE TITLE
Lines out of order Ang 1

### ISSUE THREAD

**Issue by maneetpaul** [KhalisFoundation/sttm-desktop#341]
![screen shot 2018-10-06 at 10 47 38 am](https://user-images.githubusercontent.com/10658257/46572530-7230bd00-c955-11e8-9f53-85a2331d0315.png)

**Comment by ManjotS** [comment]
We had this issue on web. Please use order by used in banidb api v1 php.

**Comment by maneetpaul** [comment]
This is fixed in 4.2
