### ISSUE TITLE
Update UI for Surfacing Banis

### ISSUE THREAD

**Issue by maneetpaul** [KhalisFoundation/sttm-desktop#352]
Please update the UI for both Compact View and Presenter View to accommodate surfacing of various Banis. See comments for mock-ups

**Comment by tsingh777** [comment]
@maneetpaul @saintsoldierx Mocks for what the ui should look like when you go to the different options would very useful.

**Comment by maneetpaul** [comment]
As discussed over slack, see below mock-up. When clicking on an icon, the list should take over the search panel. When clicking on a bani, it will appear on the bottom left quadrant where shabads normally appear when opened. 

![image 3](https://user-images.githubusercontent.com/10658257/50253823-8014ac80-03a0-11e9-90d9-dbff3af62d24.png)

**Comment by maneetpaul** [comment]
Closing this and will address in the other tickets.
