### ISSUE TITLE
Surface Sundar Gutka

### ISSUE THREAD

**Issue by maneetpaul** [KhalisFoundation/sttm-desktop#354]
Surface all Banis avaialble in Sundar Gutka

**Comment by maneetpaul** [comment]
Let's add Anand Sahib + Saloak to the top of the list when we surface Sundar Gutka

**Comment by ManjotS** [comment]
that is bani ID 1000 aka anand6

**Comment by ManjotS** [comment]
Banis between 1000 and 2000 are in STTM desktop namespace, ie should show first

**Comment by maneetpaul** [comment]
Mock-up of what we are trying to achieve. 

- All the tiles should be written in Gurmukhi
- Nitnem should be 7 Banis, including Rehras and Sohila Sahib
- Do not include a Favorites section, we will come back to this in a future Sprint

![image 5](https://user-images.githubusercontent.com/10658257/50996477-fc0d9a80-14ef-11e9-9275-8b76be778b72.png)

**Comment by ManjotS** [comment]
lets base popular off top 5-7 in google analytics for SG for now and come
back and revisit in future how to make that dynamic based on sttm and SG
stats.

**Comment by maneetpaul** [comment]
@ManjotS @tarunsingh5 can we get the top 5-7 banis that are used in SG listed here? (excluding Nitnem banis)
