### ISSUE TITLE
4.2 causes app to become unusable on windows 7

### ISSUE THREAD

**Issue by maneetpaul** [KhalisFoundation/sttm-desktop#356]
![fb961531-e6fd-4853-94fa-682fe785c844](https://user-images.githubusercontent.com/10658257/47935404-6b836000-de97-11e8-8f6e-b587b40b5e29.png)

**Comment by SukhmanpreetSingh** [comment]
I am Also Facing

**Comment by maneetpaul** [comment]
This is being addressed in PR #357 

Bugs found in the beta version: 

- Windows 7: Ang 1 showing mool mantar out of order (this was a known issue prior to 4.2)
- Windows 7: Akhand Paath View not working
- Mac & All Windows: Auto Play not working consistently
