### ISSUE TITLE
If updater is aborted at right time, it clean uninstalls

### ISSUE THREAD

**Issue by ManjotS** [KhalisFoundation/sttm-desktop#368]
Windows 10 user was trying to get rid of windows to get to interface, clicked update, cmd popped up, clicked x on it, then clicked a button on a dialog (didnt see what it was). application immediately closed and icon then disappeared from desktop.

**Comment by prebhdevsingh** [comment]
need more details on what the dialog box was. Closing for now unless we can get more details.
