### ISSUE TITLE
The history tab is no longer a history tab (needs separate icon/title)

### ISSUE THREAD

**Issue by inderpreetsingh** [KhalisFoundation/sttm-desktop#395]
History tab now includes 
* themes
* insert
* display
* others
* history

So it needs a 
* [ ] New Icon
* [ ] New title
* [ ] Can we think of better name for others tab?

<img width="370" alt="screenshot 2018-12-24 at 1 31 51 pm" src="https://user-images.githubusercontent.com/1131610/50394015-4d8ff880-0780-11e9-96eb-81597ca1a631.png">

*the icon that needs change is the middle one in shot below (sorry for highlighting wrong one in screenshot)

<img width="197" alt="screenshot 2018-12-24 at 1 29 31 pm" src="https://user-images.githubusercontent.com/1131610/50394038-7fa15a80-0780-11e9-976f-a74387822e47.png">

**Comment by maneetpaul** [comment]
I believe we addressed this
