### ISSUE TITLE
Show vishrams at all places

### ISSUE THREAD

**Issue by inderpreetsingh** [KhalisFoundation/sttm-desktop#397]
* [x] All themes
* [ ] Chromecast
* [ ] Obs

**Comment by inderpreetsingh** [comment]
@maneetpaul veerji, just a reminder that this is not done in case we want to scope it.

**Comment by tarunsingh5** [comment]
i think OBS is the only thing left right? @maneetpaul

**Comment by maneetpaul** [comment]
Correct @tarunsingh5 . @inderpreetsingh I can make a separate ticket just for that if you'd like?

**Comment by maneetpaul** [comment]
I am going to close this and make a new one for BaniOverlay
