### ISSUE TITLE
When we minimize there should be no menu icon.

### ISSUE THREAD

**Issue by inderpreetsingh** [KhalisFoundation/sttm-desktop#398]
<img width="537" alt="screenshot 2018-12-07 at 5 03 16 pm" src="https://user-images.githubusercontent.com/1131610/50394138-68af3800-0781-11e9-9af0-722982e935fb.png">

Clicking on menu icon here should either expand the panel back or there should be no menu icon at all.

**Comment by prebhdevsingh** [comment]
Menu icon doesn't seem to do anything when in the expanded view either. Can you check @inderpreetsingh ?

**Comment by Gauravjeetsingh** [comment]
Fixed in latest
