### ISSUE TITLE
Add ability to hide quick tools by preference

### ISSUE THREAD

**Issue by sukhpalsingh** [KhalisFoundation/sttm-desktop#406]
Currently quick tools are enabled for everyone. It will be nice to hide this by settings so that it does not distract to the users who don't need this quick settings.

**Comment by maneetpaul** [comment]
Quick tools is not appearing in the alpha build even though it is selected as on. 
![screen shot 2019-01-22 at 9 42 54 am](https://user-images.githubusercontent.com/10658257/51542811-1d448400-1e2a-11e9-9bb8-59612c589a59.png)

**Comment by maneetpaul** [comment]
Ignore the previous comment. Quick tools appeared when I opened a Shabad.
