### ISSUE TITLE
Update Settings to include Bani Length for SG

### ISSUE THREAD

**Issue by maneetpaul** [KhalisFoundation/sttm-desktop#437]
When we surface SG there needs to be a way to choose Bani Length

**Comment by maneetpaul** [comment]
@inderpreetsingh  - can we change this so it is a dropdown with options for "Short", Medium", "Long", and "Very Long"

Need to stay consistent with the Sundar Gutka app

**Comment by inderpreetsingh** [comment]
@maneetpaul got it.
