### ISSUE TITLE
have designers change waheguroo text button into something with sun rays

### ISSUE THREAD

**Issue by tarunsingh5** [KhalisFoundation/sttm-desktop#46]
some kind of button with sun rays or something that makes it more button like

http://us.123rf.com/450wm/yuravector/yuravector1602/yuravector160200021/54334817-comic-book-explosion-illustration-retro-pop-art-speech-bubble-with-dots-square-fight-stamp-for-card-.jpg?ver=6

**Comment by tarunsingh5** [comment]
Obsolete? @ManjotS @navdeepsinghkhalsa

**Comment by ManjotS** [comment]
this was for the old preferences which no longer exist.
