### ISSUE TITLE
Announcement text box not very visible

### ISSUE THREAD

**Issue by harindersiingh** [KhalisFoundation/sttm-desktop#462]
The font in the announcement text box should be larger and should be black. The current colour and padding make it difficult to read while typing.

**Comment by saintsoldierx** [comment]
![image](https://user-images.githubusercontent.com/27791330/51806072-371b0800-222a-11e9-8233-f7a432feb006.png)
You are saying in this box? The text is same size as the other labels, but you want it to be larger, bolder, separated properly ?

**Comment by harindersiingh** [comment]
Yes perfect!, currently when you type in the box the font colour is grey and not very visible. I think this is more the case in darker themes.

**Comment by saintsoldierx** [comment]
Ok we will work on that. Thank you for reporting this.

**Comment by tarunsingh5** [comment]
@maneetpaul just so this is on his radar

**Comment by inderpreetsingh** [comment]
Is it still a bug?

<img width="602" alt="Screenshot 2019-04-21 at 1 37 44 PM" src="https://user-images.githubusercontent.com/1131610/56467299-c9eacd80-643a-11e9-8622-4bde41ae7b2b.png">

This is what I see.

**Comment by maneetpaul** [comment]
This should be resovled
