### ISSUE TITLE
spacing of the nav header in non presenter mode needs little love.

### ISSUE THREAD

**Issue by inderpreetsingh** [KhalisFoundation/sttm-desktop#465]
<img width="494" alt="screenshot 2019-02-01 at 10 29 52 pm" src="https://user-images.githubusercontent.com/1131610/52137592-ed3e8180-2670-11e9-92db-5300c89b12ba.png">

Vertical spacing is little off.

**Comment by sukhpalsingh** [comment]
I don't see this off in linux. Is this something related to environment?

The below is how i am seeing.

<img src="https://user-images.githubusercontent.com/5441960/53009864-2d32a080-3488-11e9-81c5-8ac3d7208a9a.png" width="300" />
