### ISSUE TITLE
Show a check next to lines already shown

### ISSUE THREAD

**Issue by tarunsingh5** [KhalisFoundation/sttm-desktop#48]

**Comment by inderpreetsingh** [comment]
https://github.com/KhalisFoundation/sttm-core/pull/6

<img width="328" alt="seen_check" src="https://user-images.githubusercontent.com/1131610/36717972-1de8c4c8-1bc6-11e8-8d4e-d862749036df.PNG">

**Comment by tarunsingh5** [comment]
has been pushed to master
