### ISSUE TITLE
Whats new button in alpha build does nothing

### ISSUE THREAD

**Issue by tarunsingh5** [KhalisFoundation/sttm-desktop#482]

**Comment by maneetpaul** [comment]
This button should just open the changelog. 

Non-critical, I will add this to the Sprint for a future release. 

Thanks for logging a ticket @tarunsingh5

**Comment by tsingh777** [comment]
This is because the API is returning an Error. Happening in Production app as well.

requests to `http://api.sikhitothemax.org/messages/desktop/`
```
{
 "error": true,
 "data": {
    "fatal": false,
    "errno": 45028,
    "sqlState": "HY000",
    "code": "ER_GET_CONNECTION_TIMEOUT"
 }
}
```

@ManjotS can you take a look?

**Comment by ManjotS** [comment]
I restarted the endpoints.

**Comment by tsingh777** [comment]
Structure for the returned object changed after [KhalisFoundation/sttm-api@4713a02#diff-c40631934dd21440306b46f31bcedab7](https://github.com/KhalisFoundation/sttm-api/commit/4713a024b16af8ae022c6120027f96a4fc75a4cf#diff-c40631934dd21440306b46f31bcedab7)

PR to read new structure opened
