### ISSUE TITLE
Quick tools should overlay on top of the slide, not push everything over

### ISSUE THREAD

**Issue by maneetpaul** [KhalisFoundation/sttm-desktop#487]
![quick tools](https://user-images.githubusercontent.com/10658257/52670809-88442080-2ee7-11e9-87c4-d3f9c6230a53.gif)

**Comment by inderpreetsingh** [comment]
It used to be like that, but then it was requested to be changed. 🙏

**Comment by inderpreetsingh** [comment]
I believe we should start giving the "why" whenever we ask for a change in interface/design. 🙏

**Comment by maneetpaul** [comment]
Hm curious to why it was changed. The current way pushes everything over. Which makes the text formatted differently than what is actually being displayed.
