### ISSUE TITLE
Preference are getting lost after closing the app

### ISSUE THREAD

**Issue by sukhpalsingh** [KhalisFoundation/sttm-desktop#507]
It used to load the saved preferences even after reopening the application after close but in latest version it is not loading the saved preferences any more.

The default preference are getting loaded and database is getting download on every start.

The issue has been identified in windows 10 and linux for 4.4 version (production release)

**Comment by maneetpaul** [comment]
Thank you for letting us know @sukhpalsingh. We just released 4.4.1 that fixes this.
