### ISSUE TITLE
Salok shows before Anand Sahib on Windows 7

### ISSUE THREAD

**Issue by maneetpaul** [KhalisFoundation/sttm-desktop#528]
<img width="1358" alt="Screen Shot 2019-03-11 at 12 27 13 PM" src="https://user-images.githubusercontent.com/10658257/54140086-4086bb00-43f9-11e9-9b51-f3ea1a55f58c.png">

**Comment by tsingh777** [comment]
https://github.com/KhalisFoundation/sttm-desktop/pull/529
