### ISSUE TITLE
Add ability for anand karaj, adv, sg decks

### ISSUE THREAD

**Issue by tarunsingh5** [KhalisFoundation/sttm-desktop#53]
This will have a few parts.

The first part is to incorporate the SG app for presentation only. This will only draw off the sttm db though.

Second part is to incorporate the "Sikh wedding anand karaj" slide deck gurdwaras use and have it work the same as a searched session. I would also include the keertan anand sahib and other premade decks gurdwaras need.

**Comment by tarunsingh5** [comment]
These can maybe go where @inderpreetsingh is adding the random/hukamnama

**Comment by inderpreetsingh** [comment]
@tarunsingh5 I have added option for anand karaj, (4 laanva). 
* Is there anything else needed for anand karaj?
* Advertisements I think can be done via announcement section. If not, in what form would they be? I am thinking of image advertisements, where users can browse an image (Poster / flyer) to show on screen. What do you think?
* What are `sg decks`?

**Comment by tarunsingh5** [comment]
Adv = asa di vaar

**Comment by inderpreetsingh** [comment]
That makes sense!

**Comment by ManjotS** [comment]
I think for anand karaj deck, this should be a custom slide deck option with anand karaj as one of the available decks, this makes it more extensible in the future

**Comment by maneetpaul** [comment]
to be continued in #233 and #141
