### ISSUE TITLE
Verify Daily Hukamnama works across all platforms

### ISSUE THREAD

**Issue by maneetpaul** [KhalisFoundation/sttm-desktop#540]
Win7 was showing a different one when I was QA'ing 4.5

**Comment by tsingh777** [comment]
I'm seeing a difference in the what windows is showing verses mac. win7 and win10 looked the same though.

**Comment by tarunsingh5** [comment]
is this still an issue?

**Comment by prebhdevsingh** [comment]
this seems to be working on both Mac and Win, showing same hukamnama as STTM web.
