### ISSUE TITLE
Banis should appear in history

### ISSUE THREAD

**Issue by maneetpaul** [KhalisFoundation/sttm-desktop#552]
- opening a Bani from SG should appear in history
- same with Anand Sahib (Bhog) in shortcut tray

Need a way to differentiate Banis vs Shabads in this history list. Maybe with a highlight color or a colored square next to the line. cc: @saintsoldierx

**Comment by inderpreetsingh** [comment]
when we click on next shabad, prev shabad - that also does not appear in history. So wasn't history meant just for search history?

**Comment by maneetpaul** [comment]
Previously Shabad searches were the only thing that made sense. But now that we've added Banis, it does make sense to include these too. People will definitely be going back and forth between Banis and Shabads. Example: Asa Kee Vaar.

**Comment by tarunsingh5** [comment]
+1 to the ADV use case
