### ISSUE TITLE
Refactor: Let's breakdown search.js and viewer.js

### ISSUE THREAD

**Issue by inderpreetsingh** [KhalisFoundation/sttm-desktop#554]
These are big files reaching KLOC. A lot of code is interdependent in ways which will increase the cost to edit, and cost to debug soon.

**Comment by navdeepsinghkhalsa** [comment]
I can take this on

**Comment by maneetpaul** [comment]
I am adding this to the technical debt Sprint which will be 5.2.1

**Comment by prebhdevsingh** [comment]
should this still be open?

**Comment by maneetpaul** [comment]
Part of the refactor we are doing. This can be closed.
