### ISSUE TITLE
Double Mangals Appearing in SG Banis

### ISSUE THREAD

**Issue by maneetpaul** [KhalisFoundation/sttm-desktop#557]
Some Banis are showing mangals twice. Need to add an option to choose mangal position (similar to the setting that exists for SG mobile app)

<img width="781" alt="Screen Shot 2019-04-01 at 2 01 01 PM" src="https://user-images.githubusercontent.com/10658257/55349064-bde89d00-5486-11e9-9e36-4ec0e35900c1.png">

**Comment by ManjotS** [comment]
the query should be where != (blacklist vs whitelist)

Mangalposition column can be above, current, null, or blank

null or blank should always be included.

**Comment by maneetpaul** [comment]
Still having some issues with this:

<img width="1383" alt="Screen Shot 2019-04-22 at 3 32 55 PM" src="https://user-images.githubusercontent.com/10658257/56521962-f292c600-6513-11e9-8938-395379c5a530.png">
