### ISSUE TITLE
Split line on vishraam

### ISSUE THREAD

**Issue by tarunsingh5** [KhalisFoundation/sttm-desktop#563]
Split line on major vishraam

**Comment by ManjotS** [comment]
I made a ticket for this ~2 years ago

**Comment by maneetpaul** [comment]
Can you elaborate on what you mean by this? The line should break on a major vishraam? Regardless of where it is in the line?

**Comment by tarunsingh5** [comment]
split on the long vishraam - there arent that many lines w/ multiple long vishraams, if so, split on the 2nd one

**Comment by maneetpaul** [comment]
@tarunsingh5 - let's discuss this more over Slack. I have concerns that this will cause issues on some resolutions or TVs in terms of sizing and space

**Comment by maneetpaul** [comment]
#33 duplicate
