### ISSUE TITLE
Add ability to hide side panel w/ SG and AK shortcuts

### ISSUE THREAD

**Issue by tarunsingh5** [KhalisFoundation/sttm-desktop#571]
use left and right arrows to allow users to expand and collapse the side bar (just as they are able to collapse and expand the shortcut tray)

**Comment by maneetpaul** [comment]
Will work on this along with other keyboard shortcuts in a future Sprint

**Comment by prebhdevsingh** [comment]
this doesn't seem like a big issue with the latest UI - the left menu doesn't take up a lot of space. @tarunsingh5 going to close this unless you have something specific in mind.
