### ISSUE TITLE
Dasam Bani index

### ISSUE THREAD

**Issue by tarunsingh5** [KhalisFoundation/sttm-desktop#59]
Provide index of major banis by Guru Gobind Singh Ji similar to STTM2

**Comment by tarunsingh5** [comment]
@inderpreetsingh can you use the ang search to do this - see https://www.sikhitothemax.org/index for which angs map to which banis

**Comment by tarunsingh5** [comment]
@navdeepsinghkhalsa @ManjotS @prebhdevsingh please provide feedback here as well

**Comment by ManjotS** [comment]
Let's get the index on web and then have desktop mirror it?
