### ISSUE TITLE
5.0 Beta QA Notes

### ISSUE THREAD

**Issue by maneetpaul** [KhalisFoundation/sttm-desktop#596]
- [x] Windows 7

- [x] Windows 10

- [x] macOS

**Comment by inderpreetsingh** [comment]
Tested on all the OS. I don't see any new issues. We do have the existing hukamnama and autoplay issue which has already been reported since few versions. 🙏

**Comment by maneetpaul** [comment]
Going to document feedback from beta testers here. Will make separate tickets as needed:

- Font size for the Bani List could be a bit larger 
- When viewing the SG bani list, clicking on the side (outside the UI on the blurry area) should close out the list, rather than needing to press the X
- Changelog sometimes ends up behind the app when launching 
- When scrolling through lines really fast (using arrow keys) it is not very fluid (I have a video, but need to test this on a few more machines)

**Comment by tarunsingh5** [comment]
@maneetpaul can we close this out?
