### ISSUE TITLE
Error message when attempting to open second instance of STTM

### ISSUE THREAD

**Issue by maneetpaul** [KhalisFoundation/sttm-desktop#607]
It opens up the first instance and then displays this error message. 

The app continues to work just fine, this is not critical.
<img width="1248" alt="Screen Shot 2019-05-06 at 8 04 57 PM" src="https://user-images.githubusercontent.com/10658257/57262525-767f9e80-703a-11e9-8b55-22bb2a39f708.png">

**Comment by tsingh777** [comment]
is this a regression of https://github.com/KhalisFoundation/sttm-desktop/issues/542 or something new?

**Comment by maneetpaul** [comment]
I want to say they are related. #542 does work, however, it is just showing this error message.

**Comment by tsingh777** [comment]
Fixed by #619
