### ISSUE TITLE
Keyboard shortcut for waheguru slide

### ISSUE THREAD

**Issue by tsingh777** [KhalisFoundation/sttm-desktop#623]

**Comment by AkalUstat** [comment]
@navdeepsinghkhalsa ji i would like to tackle this one for my first issue. Is that fine?

**Comment by tsingh777** [comment]
@maneetpaul @saintsoldierx can you let @AkalUstat know which key to map. maybe `crtl+w` ?

**Comment by AkalUstat** [comment]
i dont think cmd/ctrl + w would work cause it just seems to hide/close the window

**Comment by AkalUstat** [comment]
closed via #629
