### ISSUE TITLE
Bring back old theme for desktop

### ISSUE THREAD

**Issue by ManjotS** [KhalisFoundation/sttm-desktop#625]
Please select which platform you are using:-
Desktop Version

Feedback Type
Enhancements

What went wrong?
Theme color : Long back we used to have Kesari/yellow color fonts on dark blue (all solid)  background ?  Can we get that one. Many requested from our Gurdwara Sangat for that combination on the screen.
 
What should have happened instead?

    
How can the issue be recreated by our team?

Which web browser are using?
 

Operating System

Name
Channy Singh

**Comment by prebhdevsingh** [comment]
We have a Khalsa Gold theme, and a number of newer themes have been rolled out since this ticket was created. Will close this unless we get the same feedback from other users.
