### ISSUE TITLE
Scroll View (multi-line)

### ISSUE THREAD

**Issue by AkalUstat** [KhalisFoundation/sttm-desktop#627]
Sorta like when a phone is connected to a projector and in igurbani we can scroll through the lines. Maybe have something similar on desktop. Instead having to do each line individually. This may be benefitial for samagams when either the lines are switched through quickly or when the sangat just wants to see multiple lines (more than the two that we have; and their translations too. Im rambling. if ur confused, ask me for clarification

**Comment by maneetpaul** [comment]
Akhand view should cover this. We will be enhancing that to make it more user-friendly and functional. But it solves this issue.
