### ISSUE TITLE
Background Shadow inconsistancy. 

### ISSUE THREAD

**Issue by AkalUstat** [KhalisFoundation/sttm-desktop#633]
the deployment of background shadow seems to deploy a little late on the shortcut tray. It also leaves a little later on the shortcut tray. 
<a href="https://imgflip.com/gif/31y49r"><img src="https://i.imgflip.com/31y49r.gif" title="made at imgflip.com"/></a>

**Comment by prebhdevsingh** [comment]
@AkalUstat seems like load times have been improved. Please let me know if this is still an issue.
