### ISSUE TITLE
Windows shortcuts broken 

### ISSUE THREAD

**Issue by AkalUstat** [KhalisFoundation/sttm-desktop#637]
Ctrl + m (minimize), ctrl + u (check for updates) ,and ctrl + w (close window) do not work. Not sure if ctrl + h (minimize again; might be mac only) if supported, but if it is, then its broken. 

Ctrl + a, ctrl + x, ctrl + v, ctrl + z, and ctrl + c work. 

checked on @prebhdevsingh's and @gurjeetsingh's laptops

**Comment by prebhdevsingh** [comment]
seems like this issue has been fixed, please re-open if this is still an issue.
