### ISSUE TITLE
Bani Overlay having issues with Sundar Gutka

### ISSUE THREAD

**Issue by maneetpaul** [KhalisFoundation/sttm-desktop#643]
When going through Rehras Sahib (haven't confirmed with other banis), the overlay will randomly display "Rehras Sahib" instead of the correct line (the viewer is working fine, this only impacts bani overlay). If you go back/forward a line it will fix itself. But happens randomly throughout Rehras.

![banioverlay bug](https://user-images.githubusercontent.com/10658257/58443735-de695800-80c1-11e9-88d8-87a34e12d20c.gif)

**Comment by tsingh777** [comment]
can you narrow down to which bani lengths?

**Comment by maneetpaul** [comment]
Verified on all lengths. Happens relatively quickly once you start going down the bani.

**Comment by maneetpaul** [comment]
Issue being reported again in 5.3.2

**Comment by maneetpaul** [comment]
This seems to be fixed
