### ISSUE TITLE
Search in english

### ISSUE THREAD

**Issue by ManjotS** [KhalisFoundation/sttm-desktop#644]
Please select which platform you are using:-
Desktop Version

Feedback Type
Enhancements

What went wrong?
Can you please add the search function in English mode with first letter of each word? It is missing.
 
What should have happened instead?

    
How can the issue be recreated by our team?
Search functions are not same in English mode as options available in Punjabi/Gurmukhi. Only one option available.
It is hard to type full word in English (due to convertion of gurmukhi to English) as compared to search with first letter of each word in gurmukhi mode.

Which web browser are using?
 

Operating System

Name
Parmjit Singh

**Comment by maneetpaul** [comment]
#614 duplicate
