### ISSUE TITLE
Random shabad in desktop app

### ISSUE THREAD

**Issue by tarunsingh5** [KhalisFoundation/sttm-desktop#66]
In addition to random shabad in desktop app, it might be good to have Darbar Sahib hukamnama as well.

If that SJ Gurdwara app goes through it might be even better to have this as configuration to let users decide which hukamnama sahib they want to see. e.g. Today's San Jose Gurdwara hukamnama.

**Comment by inderpreetsingh** [comment]
Just confirming, so i have to do these things
- [ ]  Add a random Shabad in custom slides option
- [ ] Add a hukamnama slide in custom slides option (use https://api.gurbaninow.com/v2/hukamnama/today ?)
- [ ] Allow hukamnama to be configured

**Comment by tarunsingh5** [comment]
launched
