### ISSUE TITLE
add ability to pull/check for new db changes

### ISSUE THREAD

**Issue by tarunsingh5** [KhalisFoundation/sttm-desktop#67]
Currently the app is pushed updated, you should also be able to pull for them rather than wait on them

**Comment by ManjotS** [comment]
I think there should be a force option too in case theres some weird local corruption

**Comment by tsingh777** [comment]
Closing the app and reopening should handle this.

**Comment by maneetpaul** [comment]
@ManjotS @tsingh777 do we use version numbers for the DB? Similar to how we can see the desktop app is running version 6.0, etc...we can add visibility to see which version of the DB is being used.

**Comment by ManjotS** [comment]
DB is identified by an MD5. I am not sure if the banidb-export app adds
anything to the realm db.

**Comment by tarunsingh5** [comment]
@ManjotS - can we close this out since restarting the app auto-checks for a new db?
