### ISSUE TITLE
Preference Option is not showing in the linux

### ISSUE THREAD

**Issue by sukhpalsingh** [KhalisFoundation/sttm-desktop#69]
The preference option in the file menu does not show up in linux. Not sure if this is an issue in window or mac as well. Others options do show up.

**Comment by tarunsingh5** [comment]
Confirmed this behavior is happening

**Comment by tarunsingh5** [comment]
@inderpreetsingh this was addressed in your pull request right?

**Comment by inderpreetsingh** [comment]
Yes, at-least partially it's solved. Preferences menu shows up in linux but it does not show up from `file->preferences`.

**Comment by tarunsingh5** [comment]
@inderpreetsingh can we fix this fully?

**Comment by inderpreetsingh** [comment]
@tarunsingh5 ha'nji it's already fixed. We can close this issue.
