### ISSUE TITLE
Add toggle to extend Mool Mantar slide to longer version

### ISSUE THREAD

**Issue by irvanjitsingh** [KhalisFoundation/sttm-desktop#706]
There should be a universal toggle that sets both Bani Length for Sundar Gutka and Mool Mantar slide length (as well as any other relevant bani lengths for other current or future slides where sangat and/or gurdwara maryada may differ from SGPC).

**Comment by tarunsingh5** [comment]
i think this issue is moot given akal takhat sahibs ruling on mool mantar and given the ability to choose bani lengths already

**Comment by maneetpaul** [comment]
We are going to make the bani length toggle more accessible
