### ISSUE TITLE
Move to portfinder

### ISSUE THREAD

**Issue by tsingh777** [KhalisFoundation/sttm-desktop#737]
https://github.com/joeferner/node-openport is deprecated. The doc recommend moving to https://github.com/http-party/node-portfinder

**Comment by SikhNerd** [comment]
Is using the gurugadi dates a hard requirement? node-portfinder only takes a range...

**Comment by tsingh777** [comment]
Not a hard requirement. More like an easter egg.

**Comment by Gauravjeetsingh** [comment]
Switched to portfinder, closing this now.
