### ISSUE TITLE
Consolidate Jaap Sahib Slides

### ISSUE THREAD

**Issue by maneetpaul** [KhalisFoundation/sttm-desktop#741]
Going through Jaap sahib on desktop is a challenge. Each line is a separate slide. There must be a thousand times you need to press the arrow key to get through the whole bani. Maybe we make it so each slide is a pauree rather than an individual each line?

**Comment by tsingh777** [comment]
Maybe a consolidated version can be listed as a separate bani? I can see a use case of just having one line showing at a time during katha.  Some paurees are longer so it might get cramped on those slides.  Does Akhand Paatth View not help?
