### ISSUE TITLE
autocombine lines of 20 characters or less

### ISSUE THREAD

**Issue by ManjotS** [KhalisFoundation/sttm-desktop#76]
Ie a short line should combine with next line that has number.

"Ta ki gehi man ot" as example.

**Comment by tarunsingh5** [comment]
dont think we need this anymore - thoughts?

**Comment by ManjotS** [comment]
yes we do. I just filed this at the samagam. it makes display nicer.

**Comment by maneetpaul** [comment]
Similar to #127
