### ISSUE TITLE
Show meta data for shabads

### ISSUE THREAD

**Issue by ManjotS** [KhalisFoundation/sttm-desktop#765]
How we can see panna number as well as whos bani it is?

Please select which platform you are using:-
Desktop Version

Feedback Type
Questions

What went wrong?

 
What should have happened instead?

    
How can the issue be recreated by our team?

Which web browser are using?
 

Operating System

Name
Harminder Singh

**Comment by prebhdevsingh** [comment]
assigning to Aman Singh since it needs some UX thought.

**Comment by saintsoldierx** [comment]
This is how I envision it. 

1. We need to make the search fields more like search fields.
2. Separate ang search, make it more obvious.
3. When hovering over a line, it should highlight and show english translation at bottom.
4. Users can filter results by writer/raag

![image](https://user-images.githubusercontent.com/27791330/113819398-19ad2700-972e-11eb-811d-7444703e0e43.png)

**Comment by Gauravjeetsingh** [comment]
We are already showing meta in search, closing this
![image](https://github.com/KhalisFoundation/sttm-desktop/assets/1990932/f3b7d884-a35e-43c3-96b8-97d9c92b2f4a)
