### ISSUE TITLE
port 2 letter search from banidb api

### ISSUE THREAD

**Issue by ManjotS** [KhalisFoundation/sttm-desktop#77]

**Comment by tarunsingh5** [comment]
@inderpreetsingh is this something you can work on? 

@ManjotS  please provide inder w/ context

**Comment by ManjotS** [comment]
Basically if the length of the query is 2 letters (1 is not allowed, but minimum is 2 now), then order by firstletterlen, if it is 3 or more letters, then keep the original order by. Here is the corresponding api php:

```
$query                     .= ' ORDER BY ';
  if ($type < 2 && strlen($originalQ) < 3) { 
    $query                   .= 'FirstLetterLen, ';
  }
  $query                     .= 'ShabadID ASC';
```

**Comment by ManjotS** [comment]
this only applies for first letter search (anywhere or from beginning)

**Comment by inderpreetsingh** [comment]
@tarunsingh5 yes I can take this on.

**Comment by tarunsingh5** [comment]
this is fixed in prod
