### ISSUE TITLE
sttm logo on slides is not clear on low quality projectors

### ISSUE THREAD

**Issue by ManjotS** [KhalisFoundation/sttm-desktop#78]

**Comment by tarunsingh5** [comment]
obsolete

**Comment by ManjotS** [comment]
This is still an issue. Its washed out at almost every gurdwara I have been to unless you go close up.

**Comment by tarunsingh5** [comment]
what about in v4?

**Comment by ManjotS** [comment]
its an issue in the following themes:
light,
dark,
low light dark
