### ISSUE TITLE
User created display presents

### ISSUE THREAD

**Issue by AkalUstat** [KhalisFoundation/sttm-desktop#780]
Basically user can save multiple setups and just switch between them.
Examples:
Preset 1: Gurmukhi + translit (in apv)
Present 2: everything display (not apv)
..and so on

**Comment by hpreets** [comment]
Or to take it the next step, we can allow pre-defined (and user-defined) templates that gives more control. For e.g. user can define the layout of where it shows Punjabi meaning before or after English meaning, English transliteration before or after English meaning. 
Advanced User can themselves define templates that control the padding, the margins, the colors for vishraams, colors for Gurbani Text, Punjabi Meaning Text, English Meanings Text etc. - similar to how it can be done in STTM 2008 where we can create Powerpoint templates ourselves and select one of the templates.

**Comment by maneetpaul** [comment]
Duplicating of #766
