### ISSUE TITLE
Gurbani Text in Hindi

### ISSUE THREAD

**Issue by hpreets** [KhalisFoundation/sttm-desktop#781]
Are there any plans to include Gurbani Text in Hindi as one of the display options? Much of Sangat in India would love to have Hindi option too in parts outside Punjab like Delhi, Maharashtra, UP and various other places.
You might think it as a bad idea but as a beta release, we can use same text as Gurbani text but present it with a different Hindi font, and replace few characters that do not translate correctly. For e.g. translating ਰਜਾਈ from Gurmukhi will translate to रजाइी in Hindi using Hindi font, and hence will have to be corrected to रजाई by replacing इी with ई

**Comment by ManjotS** [comment]
Yes, this is close to finished.

**Comment by ManjotS** [comment]
Please check anvaad-js project and help us with character translations!
