### ISSUE TITLE
strange repeating issue in search

### ISSUE THREAD

**Issue by ManjotS** [KhalisFoundation/sttm-desktop#79]
![image](https://user-images.githubusercontent.com/644885/36635963-4f327f2a-1972-11e8-84c7-6c991ffb0a6c.png)

**Comment by tarunsingh5** [comment]
this appears to be fixed in prod - can we confirm? @prebhdevsingh @ManjotS

**Comment by ManjotS** [comment]
what was original cause

**Comment by tarunsingh5** [comment]
closing as this is likely due to #281
