### ISSUE TITLE
Search and preview overlapping

### ISSUE THREAD

**Issue by Harjot1Singh** [KhalisFoundation/sttm-desktop#8]
The search and preview boxes are not aligned properly and are overlapping the navbar:
![image](https://user-images.githubusercontent.com/1184274/34364885-32647fca-ea82-11e7-981b-3286f32a4160.png)

**Comment by navdeepsinghkhalsa** [comment]
Thank you for the heads-up on this, @Harjot1Singh. Confirmed that this is a bug

**Comment by tarunsingh5** [comment]
fixed in 3.3
