### ISSUE TITLE
Show Anand Sahib (Bhog) in Ceremonies 

### ISSUE THREAD

**Issue by maneetpaul** [KhalisFoundation/sttm-desktop#816]
It is the last option in SG currently

**Comment by inderpreetsingh** [comment]
@maneetpaul veerji can we get UI for extra ceremonies?

Do we repeat the same? If yes, what would be themes for each of them?

**Comment by inderpreetsingh** [comment]
P.S Also we have "Anand Sahib and Salok" in ceremonies. Is that this one?

**Comment by saintsoldierx** [comment]
I would say keep it same, should be just like rows of ceremonies in the
existing panel. Follow same design. Theme - should be able to select any
theme if possible or have one suggested theme u think fits best with the
ceremony.
