### ISSUE TITLE
User Report: Sangat Sync not displaying code

### ISSUE THREAD

**Issue by ManjotS** [KhalisFoundation/sttm-desktop#825]
Please select which platform you are using:-
Desktop Version

Feedback Type
Bug Reports

What went wrong?
1. Launch Sikhi to the Max .exe
2. In presentation view, output to projector
3. Click  sangat sync. Click present
4. instructions are shown on screen with code "false"

The sync function is not working. it is not generating any code. Screenshot of output screen is attached
Windows 7 64 bit
sttm 6.0.0
 
What should have happened instead?
It should have shown valid code for sttm.co/org
    
How can the issue be recreated by our team?
none

Which web browser are using?
Chrome 

Operating System
Microsoft Windows

Name
Prabhdeep Singh

**Comment by prebhdevsingh** [comment]
This seems to have been fixed but I think the problem really happens when your internet connection is not stable. I'm going to close this and we'll investigate this implementation thoroughly.
