### ISSUE TITLE
Windows 7 Ceremony Title is not correct

### ISSUE THREAD

**Issue by maneetpaul** [KhalisFoundation/sttm-desktop#873]
<img width="1066" alt="Screen Shot 2019-12-03 at 10 25 53 PM" src="https://user-images.githubusercontent.com/10658257/70110120-ee876480-161b-11ea-8fd1-27609d63ffc9.png">

**Comment by prebhdevsingh** [comment]
Rendering okay now 
![image](https://user-images.githubusercontent.com/9758101/111257454-68a4e800-85d8-11eb-9ac6-23c6cd3be32e.png)
