### ISSUE TITLE
Admin code in sttm-api

### ISSUE THREAD

**Issue by tsingh777** [KhalisFoundation/sttm-desktop#879]
Think we need a column for the admin code which will sent on creation of the socket to desktop. Controller will need to supply this code in order to connect to the socket. 

Need to spike but
either `/sync/begin/${host}` needs to be updated or a new endpoint needs to be added that should return the admin code (along with the sync code? @ManjotS to confirm).

**Comment by ManjotS** [comment]
Could we keep it simple and use the sync code? 

This allows messages to be 2 way on the same stream, but only actioned upon if a pin code is seeded with a secret.

**Comment by tsingh777** [comment]
We can. I'm assuming DB will need to be updated as well as sttm-api.

**Comment by ManjotS** [comment]
Ping me today let's discuss as I don't understand.

**Comment by tsingh777** [comment]
As discussed. no changes needed in sttm-api or DB.
