### ISSUE TITLE
Customisable backgrounds

### ISSUE THREAD

**Issue by Harjot1Singh** [KhalisFoundation/sttm-desktop#9]
This would be good. Had Gurdwaras complain about the lack of this to match their "theme".

**Comment by navdeepsinghkhalsa** [comment]
Thank you for this request, Singh Jee. This is a planned feature though, admittedly, there's no issue for it on GH. We have been mostly tracking our planned features in a private JIRA instance, but we may move that here for the sake of transparency. I'll leave the issue open for further discussion until we move the JIRA issues here.

**Comment by navdeepsinghkhalsa** [comment]
Please see #6

**Comment by Harjot1Singh** [comment]
Wicked. 

Would be great to have the issues moved here, would love to contribute.
