### ISSUE TITLE
Make Bani Overlay URL more visible

### ISSUE THREAD

**Issue by saintsoldierx** [KhalisFoundation/sttm-desktop#916]
1. Need a reset button to re-load the default settings.
2. Need a show URL button as well as copy. Sometimes user needs to show URL on screen to enter on another laptop for Bani Overlay.

**Comment by maneetpaul** [comment]
@saintsoldierx if you hover over the copy icon it will display the URL. Is there more we should do there?

**Comment by saintsoldierx** [comment]
I would include URL that is always displayed if possible? I keep forgetting about the hover and im sure others may do too. I would show it at the bottom, below the preview screen on Bani Overlay, small not large font.

**Comment by saintsoldierx** [comment]
^ and put a copy button next to it or something, remove from the left side bar.

**Comment by maneetpaul** [comment]
Rough mockup

![OverlayURL](https://user-images.githubusercontent.com/10658257/72365959-4c9d7200-36c7-11ea-858e-23e23615cc55.jpg)
