### ISSUE TITLE
Need help using desktop

### ISSUE THREAD

**Issue by ManjotS** [KhalisFoundation/sttm-desktop#917]
I am not familiar with this application and how it works. I am just trying to copy a pauri from the Siri Guru Granth and paste it into Word and the Gurmukhi Font is in English letters. I have Gurmukhi font on my desktop, so what do I have to do to have the Gurmukhi font correct? Thanks

Please select which platform you are using:-
Desktop Version

Feedback Type
Questions

What went wrong?

 
What should have happened instead?

    
How can the issue be recreated by our team?

Which web browser are using?
 

Operating System

Name
Dharma Kaur Khalsa

**Comment by AkalUstat** [comment]
Desktop copies in unicode font.
