### ISSUE TITLE
change default punjabi source

### ISSUE THREAD

**Issue by ManjotS** [KhalisFoundation/sttm-desktop#924]
Default punjabi should now come from translations.pu.bdb instead of from pu.ss. (or puu.bdb)

going forward, pu.ss will be sahib singh and pu.ft is faridkot tika - both should be available

**Comment by maneetpaul** [comment]
Let's add a "Punjabi Source" setting to the "Language Settings" section. 

It should contain both options mentioned above.

**Comment by inderpreetsingh** [comment]
@maneetpaul Shouldn't it be teeka source?
