### ISSUE TITLE
Allow users to change fonts for Bani Overlay

### ISSUE THREAD

**Issue by saintsoldierx** [KhalisFoundation/sttm-desktop#930]
Users should be able to select from at least 3 different fonts on Bani Overlay and on-screen presentation.

**Comment by maneetpaul** [comment]
@saintsoldierx can you provide the fonts you had in mind to be listed?

**Comment by saintsoldierx** [comment]
1. Muli (Default) https://fonts.google.com/specimen/Muli
2. PT Serif https://fonts.google.com/specimen/PT+Serif
3. Caveat https://fonts.google.com/specimen/Caveat

Punjabi fonts should be same as web

**Comment by maneetpaul** [comment]
Making this ticket for Bani Overlay. Will make another one for the main presenter.

**Comment by maneetpaul** [comment]
![Overlay_Updates](https://user-images.githubusercontent.com/10658257/75462855-e2791d80-5952-11ea-97bf-eb195f81cdf4.jpg)
