### ISSUE TITLE
Add new vertical/classic Bani Overlay options

### ISSUE THREAD

**Issue by saintsoldierx** [KhalisFoundation/sttm-desktop#931]
See screenshot (allow for overlay on left or right)
![image](https://user-images.githubusercontent.com/27791330/72214328-7fbbe780-34b4-11ea-8a3a-bc76441f9a63.png)

**Comment by saintsoldierx** [comment]
![classic subtitles](https://user-images.githubusercontent.com/27791330/72214496-2f468900-34b8-11ea-892c-b562fb489137.jpg)

I done the above screenshot in purely CSS (as per below)
![image](https://user-images.githubusercontent.com/27791330/72214499-500ede80-34b8-11ea-8987-7bd9d7441f1c.png)

element.style {
    color: rgb(255, 255, 255);
    font-size: 7.25vh;
    height: 85%;
    text-indent: 0px;
    width: fit-content;
    margin: auto;
    padding: 0.5% 15px 0.5% 14px;
    background-color: rgba(0, 0, 0, 0.7);
}
.o-gurbani {
    font-family: 'gurbaniakharthick';
}
.content-bar {
    color: #f1c40f;
    /* left: 0; */
    /* margin: auto; */
    /* padding-left: 3vw; */
    /* padding-right: 3vw; */
    /* position: relative; */
    text-align: center;
    /* width: 100%; */
}
.gurmukhi {
    font-family: 'gurbaniakhar';
}
* {
    /* box-sizing: border-box; */
    /* margin: 0; */
    /* overflow: hidden; */
    /* padding: 0; */
}

**Comment by AkalUstat** [comment]
@saintsoldierx could you post the mockups again...gh lost them

**Comment by AkalUstat** [comment]
@saintsoldierx im not getting the same results you are with the css
