### ISSUE TITLE
Sync window should show "lock screen" after connection is made

### ISSUE THREAD

**Issue by maneetpaul** [KhalisFoundation/sttm-desktop#955]
After a user successfully connects via Bani Controller, it should automatically display the lock screen (reference #954)

**Comment by ManjotS** [comment]
I'd like for the lock screen to go away soon. Ie the ability to collaborate
should be there.

In future versions we could relay searches bidirectionally, as characters
are typed. So if the person at the laptop doesn't know if it's a v or b,
someone in Mobile can see what's typed and add or alter it live. This just
requires implementing new Messengers and listeners.
